package com.tencent.mm.plugin.appbrand.step;

import com.tencent.matrix.trace.core.AppMethodBeat;
import com.tencent.mm.plugin.appbrand.keylogger.base.a;
import com.tencent.mm.plugin.appbrand.keylogger.base.d;
import com.tencent.mm.plugin.appbrand.keylogger.base.e;
import com.tencent.mm.plugin.appbrand.keylogger.base.f;
import com.tencent.mm.plugin.appbrand.keylogger.base.i;
import com.tencent.mm.sdk.platformtools.WeChatBrands;
import java.util.ArrayList;
import java.util.List;

public final class KSProcessWeAppLaunch {
    public static final String NAME = "WeAppLaunch";
    public static final List<d> sStepNodes;
    public static a stepCheckBan = new e(NAME, "CheckBan", true, false, "封禁逻辑", 1, 1, Integer.MIN_VALUE, "");
    public static a stepColdLaunchFailed = new e(NAME, "ColdLaunchFailed", true, true, "", 1, 1, Integer.MIN_VALUE, "");
    public static a stepContainerUILaunch = new e(NAME, "ContainerUILaunch", true, true, "拉起容器UI界面", 1, 1, Integer.MIN_VALUE, "");
    public static a stepCreateMagicBrushView = new e(NAME, "CreateMagicBrushView", true, true, "", 1, 12, Integer.MIN_VALUE, "");
    public static a stepCreatePageUI = new e(NAME, "CreatePageUI", true, false, "首页界面创建", 1, 8, Integer.MIN_VALUE, "");
    public static a stepCreatePageUI_Game = new e(NAME, "CreatePageUI_Game", true, false, "首页界面创建", 1, 12, Integer.MIN_VALUE, "");
    public static a stepCreateWebViewInstance = new e(NAME, "CreateWebViewInstance", true, true, "", 1, 8, Integer.MIN_VALUE, "");
    public static a stepGenerateFuncReadyRespond = new e(NAME, "GenerateFuncReadyRespond", false, false, "webview发出的GenerateFuncReady被appservice响应 (View)", 1, 7, Integer.MIN_VALUE, "");
    public static a stepGetContact = new e(NAME, "GetContact", true, false, "", 3, 1, 2, "");
    public static a stepGetContact_CGI = new e(NAME, "GetContact_CGI", false, true, "拉contact cgi", 1, 2, Integer.MIN_VALUE, "");
    public static a stepGetContact_DB = new e(NAME, "GetContact_DB", true, true, "读取contact信息", 1, 2, Integer.MIN_VALUE, "");
    public static a stepInitRuntimeGroup = new e(NAME, "InitRuntimeGroup", true, false, "", 3, 1, 5, WeChatBrands.Business.GROUP_MP);
    public static a stepInitRuntimeGroup_Game = new e(NAME, "InitRuntimeGroup_Game", true, false, "", 3, 1, 9, "game");
    public static a stepInjectJSAppService = new e(NAME, "InjectJSAppService", true, true, "注入appservice.js (Service)", 1, 6, Integer.MIN_VALUE, "");
    public static a stepInjectJSGame = new e(NAME, "InjectJSGame", true, true, "注入game.js (Service)", 1, 10, Integer.MIN_VALUE, "");
    public static a stepInjectJSPageScript = new e(NAME, "InjectJSPageScript", true, false, "页面js注入 (View)", 1, 7, Integer.MIN_VALUE, "");
    public static a stepInjectJSWAMainContext = new e(NAME, "InjectJSWAMainContext", true, true, "注入WAMainContext.js (Service)", 1, 6, Integer.MIN_VALUE, "");
    public static a stepInjectJSWASubContext = new e(NAME, "InjectJSWASubContext", true, true, "注入WASubContext.js (Service)", 1, 6, Integer.MIN_VALUE, "");
    public static a stepInjectJSWAWebview = new e(NAME, "InjectJSWAWebview", true, true, "注入WAWebview.js (View)", 1, 7, Integer.MIN_VALUE, "");
    public static a stepInjectWAGameContext = new e(NAME, "InjectWAGameContext", true, true, "注入 WAGame.js (Service)", 1, 10, Integer.MIN_VALUE, "");
    public static a stepInjectWAGameSubContext = new e(NAME, "InjectWAGameSubContext", true, true, "注入 WAGameSubContext.js (Service) ", 1, 10, Integer.MIN_VALUE, "");
    public static a stepInjectWAPageFrameHtml = new e(NAME, "InjectWAPageFrameHtml", true, true, "注入WAPageframe.html (View)", 1, 7, Integer.MIN_VALUE, "");
    public static a stepInjectWxConfig = new e(NAME, "InjectWxConfig", true, true, "注入wxConfig (Service)", 1, 6, Integer.MIN_VALUE, "");
    public static a stepInjectWxConfig_Game = new e(NAME, "InjectWxConfig_Game", true, true, "注入wxConfig (Service)", 1, 10, Integer.MIN_VALUE, "");
    public static a stepInstallLibraries = new e(NAME, "InstallLibraries", true, true, "动态安装小程序环境所需二进制库", 1, 3, Integer.MIN_VALUE, "");
    public static a stepLaunch = new e(NAME, "Launch", true, false, "", 2, 0, 1, "");
    public static a stepPageInit = new e(NAME, "PageInit", true, false, "", 2, 5, 7, "");
    public static a stepPageInitUIGroup = new e(NAME, "PageInitUIGroup", true, false, "", 3, 7, 8, "");
    public static a stepPageInitUIGroup_Game = new e(NAME, "PageInitUIGroup_Game", true, false, "", 3, 11, 12, "");
    public static a stepPageInit_Game = new e(NAME, "PageInit_Game", true, false, "", 2, 9, 11, "");
    public static a stepPageReady = new e(NAME, "PageReady", true, false, "page ready (View)", 1, 7, Integer.MIN_VALUE, "");
    public static a stepPageReady_Game = new e(NAME, "PageReady_Game", true, false, "page ready (View)", 1, 11, Integer.MIN_VALUE, "");
    public static a stepPrepareMainProcess = new e(NAME, "PrepareMainProcess", true, true, "准备主进程通讯", 1, 3, Integer.MIN_VALUE, "");
    public static a stepPrepareResourceGroup = new e(NAME, "PrepareResourceGroup", true, false, "Launch CGI及准备小程序包", 3, 3, 4, "");
    public static a stepPrepareResourceProcess = new e(NAME, "PrepareResourceProcess", true, false, "资源准备逻辑过程", 1, 4, Integer.MIN_VALUE, "");
    public static a stepPrepareResourceSubProcessCodePkg_DB = new e(NAME, "PrepareResourceSubProcessCodePkg_DB", true, true, "使用本地缓存好的代码包打开", 1, 4, Integer.MIN_VALUE, "");
    public static a stepPrepareResourceSubProcessCodePkg_Download = new e(NAME, "PrepareResourceSubProcessCodePkg_Download", true, true, "同步下载代码包打开", 1, 4, Integer.MIN_VALUE, "");
    public static a stepPrepareResourceSubProcessLaunchWxaApp_CGI = new e(NAME, "PrepareResourceSubProcessLaunchWxaApp_CGI", true, true, "同步请求launch数据打开", 1, 4, Integer.MIN_VALUE, "");
    public static a stepPrepareResourceSubProcessLaunchWxaApp_DB = new e(NAME, "PrepareResourceSubProcessLaunchWxaApp_DB", true, true, "使用本地缓存的launch数据打开", 1, 4, Integer.MIN_VALUE, "");
    public static a stepPrepareResourceTimeout = new e(NAME, "PrepareResourceTimeout", true, true, "资源准备10s超时事件", 1, 4, Integer.MIN_VALUE, "");
    public static a stepPrepareResourceWaitForResult = new e(NAME, "PrepareResourceWaitForResult", true, false, "runtime监听过程结果", 1, 4, Integer.MIN_VALUE, "");
    public static a stepPrepareRuntime = new e(NAME, "PrepareRuntime", true, false, "", 3, 1, 3, "");
    public static a stepPrepareWebView = new e(NAME, "PrepareWebView", true, true, "准备WebView (View)", 1, 3, Integer.MIN_VALUE, "");
    public static a stepServiceInit = new e(NAME, "ServiceInit", true, false, "", 2, 5, 6, "");
    public static a stepServiceInit_Game = new e(NAME, "ServiceInit_Game", true, false, "", 2, 9, 10, "");
    public static a stepSetupConfigsPostResourcePrepared = new e(NAME, "SetupConfigsPostResourcePrepared", true, false, "资源准备完的配置解析", 1, 3, Integer.MIN_VALUE, "");
    public static a stepSurfaceAvailable = new e(NAME, "SurfaceAvailable", true, false, "SurfaceAvailable (View)", 1, 11, Integer.MIN_VALUE, "");
    public static a stepVdSync = new e(NAME, "VdSync", true, false, "第一次VdSync (View) ", 1, 7, Integer.MIN_VALUE, "");
    public static a stepWaitForAppServiceAheadPreloadDone = new e(NAME, "WaitForAppServiceAheadPreloadDone", true, true, "等待运行时预加载appservice完成 (Service)", 1, 3, Integer.MIN_VALUE, "");
    public static a stepWaitForAppServicePreloadDone = new e(NAME, "WaitForAppServicePreloadDone", true, true, "等待启动前预加载appservice完成 (Service)", 1, 3, Integer.MIN_VALUE, "");
    public static a stepWaitForCommLibConfirm = new e(NAME, "WaitForCommLibConfirm", true, true, "确定基础库版本", 1, 3, Integer.MIN_VALUE, "");
    public static a stepWaitForWebViewAheadPreloadDone = new e(NAME, "WaitForWebViewAheadPreloadDone", true, true, "等待运行时预加载webview完成 (View)", 1, 3, Integer.MIN_VALUE, "");
    public static a stepWaitForWebViewPreloadDone = new e(NAME, "WaitForWebViewPreloadDone", true, true, "等待启动前预加载webview完成 (View)", 1, 3, Integer.MIN_VALUE, "");

    static {
        AppMethodBeat.i(219589);
        ArrayList arrayList = new ArrayList();
        sStepNodes = arrayList;
        arrayList.add(new i(NAME));
        sStepNodes.add((d) stepLaunch);
        sStepNodes.add((d) stepGetContact);
        sStepNodes.add((d) stepGetContact_DB);
        sStepNodes.add((d) stepGetContact_CGI);
        sStepNodes.add((d) stepCheckBan);
        sStepNodes.add((d) stepContainerUILaunch);
        sStepNodes.add((d) stepPrepareRuntime);
        sStepNodes.add((d) stepPrepareMainProcess);
        sStepNodes.add((d) stepInstallLibraries);
        sStepNodes.add((d) stepPrepareWebView);
        sStepNodes.add((d) stepPrepareResourceGroup);
        sStepNodes.add((d) stepPrepareResourceProcess);
        sStepNodes.add((d) stepPrepareResourceWaitForResult);
        sStepNodes.add((d) stepPrepareResourceTimeout);
        sStepNodes.add((d) stepPrepareResourceSubProcessLaunchWxaApp_DB);
        sStepNodes.add((d) stepPrepareResourceSubProcessLaunchWxaApp_CGI);
        sStepNodes.add((d) stepPrepareResourceSubProcessCodePkg_DB);
        sStepNodes.add((d) stepPrepareResourceSubProcessCodePkg_Download);
        sStepNodes.add((d) stepSetupConfigsPostResourcePrepared);
        sStepNodes.add((d) stepWaitForCommLibConfirm);
        sStepNodes.add((d) stepWaitForWebViewPreloadDone);
        sStepNodes.add((d) stepWaitForWebViewAheadPreloadDone);
        sStepNodes.add((d) stepWaitForAppServicePreloadDone);
        sStepNodes.add((d) stepWaitForAppServiceAheadPreloadDone);
        sStepNodes.add((d) stepInitRuntimeGroup);
        sStepNodes.add((d) stepServiceInit);
        sStepNodes.add((d) stepInjectJSWAMainContext);
        sStepNodes.add((d) stepInjectJSWASubContext);
        sStepNodes.add((d) stepInjectJSAppService);
        sStepNodes.add((d) stepInjectWxConfig);
        sStepNodes.add((d) stepPageInit);
        sStepNodes.add((d) stepPageInitUIGroup);
        sStepNodes.add((d) stepCreatePageUI);
        sStepNodes.add((d) stepCreateWebViewInstance);
        sStepNodes.add((d) stepInjectWAPageFrameHtml);
        sStepNodes.add((d) stepInjectJSWAWebview);
        sStepNodes.add((d) stepInjectJSPageScript);
        sStepNodes.add((d) stepGenerateFuncReadyRespond);
        sStepNodes.add((d) stepVdSync);
        sStepNodes.add((d) stepPageReady);
        sStepNodes.add((d) stepInitRuntimeGroup_Game);
        sStepNodes.add((d) stepServiceInit_Game);
        sStepNodes.add((d) stepInjectWAGameContext);
        sStepNodes.add((d) stepInjectWAGameSubContext);
        sStepNodes.add((d) stepInjectJSGame);
        sStepNodes.add((d) stepInjectWxConfig_Game);
        sStepNodes.add((d) stepPageInit_Game);
        sStepNodes.add((d) stepPageInitUIGroup_Game);
        sStepNodes.add((d) stepCreatePageUI_Game);
        sStepNodes.add((d) stepCreateMagicBrushView);
        sStepNodes.add((d) stepSurfaceAvailable);
        sStepNodes.add((d) stepPageReady_Game);
        sStepNodes.add((d) stepColdLaunchFailed);
        sStepNodes.add(new f(NAME));
        AppMethodBeat.o(219589);
    }
}
