package com.tencent.mm.live.c;

import android.os.Bundle;
import com.tencent.matrix.trace.core.AppMethodBeat;
import com.tencent.mm.plugin.appbrand.jsapi.audio.JsApiGetBackgroundAudioState;
import com.tencent.mm.plugin.appbrand.jsapi.k.g;
import com.tencent.mm.plugin.appbrand.jsapi.k.r;
import com.tencent.smtt.sdk.TbsListener;
import com.tencent.thumbplayer.api.TPOptionalID;
import com.tencent.thumbplayer.core.common.TPCodecParamers;

public interface b {
    public static final a hLr = a.hLs;

    int getLiveRole();

    void registerPlugin(a aVar);

    void statusChange(c cVar, Bundle bundle);

    public static final class c extends Enum<c> {
        public static final c hLA;
        public static final c hLB;
        public static final c hLC;
        public static final c hLD;
        public static final c hLE;
        public static final c hLF;
        public static final c hLG;
        public static final c hLH;
        public static final c hLI;
        public static final c hLJ;
        public static final c hLK;
        public static final c hLL;
        public static final c hLM;
        public static final c hLN;
        public static final c hLO;
        public static final c hLP;
        public static final c hLQ;
        public static final c hLR;
        public static final c hLS;
        public static final c hLT;
        public static final c hLU;
        public static final c hLV;
        public static final c hLW;
        public static final c hLX;
        public static final c hLY;
        public static final c hLZ;
        public static final c hLt;
        public static final c hLu;
        public static final c hLv;
        public static final c hLw;
        public static final c hLx;
        public static final c hLy;
        public static final c hLz;
        public static final c hMA;
        public static final c hMB;
        public static final c hMC;
        public static final c hMD;
        public static final c hME;
        public static final c hMF;
        public static final c hMG;
        public static final c hMH;
        public static final c hMI;
        public static final c hMJ;
        public static final c hMK;
        public static final c hML;
        public static final c hMM;
        public static final c hMN;
        public static final c hMO;
        public static final c hMP;
        public static final c hMQ;
        public static final c hMR;
        public static final c hMS;
        public static final c hMU;
        public static final c hMV;
        public static final c hMW;
        public static final c hMX;
        public static final c hMY;
        public static final c hMZ;
        public static final c hMa;
        public static final c hMb;
        public static final c hMc;
        public static final c hMd;
        public static final c hMe;
        public static final c hMf;
        public static final c hMg;
        public static final c hMh;
        public static final c hMi;
        public static final c hMj;
        public static final c hMk;
        public static final c hMl;
        public static final c hMm;
        public static final c hMn;
        public static final c hMo;
        public static final c hMp;
        public static final c hMq;
        public static final c hMr;
        public static final c hMs;
        public static final c hMt;
        public static final c hMu;
        public static final c hMv;
        public static final c hMw;
        public static final c hMx;
        public static final c hMy;
        public static final c hMz;
        public static final c hNA;
        public static final c hNB;
        public static final c hNC;
        public static final c hND;
        public static final c hNE;
        public static final c hNF;
        public static final c hNG;
        public static final c hNH;
        public static final c hNI;
        public static final c hNJ;
        public static final c hNK;
        public static final c hNL;
        public static final c hNM;
        public static final c hNN;
        public static final c hNO;
        public static final c hNP;
        public static final c hNQ;
        public static final c hNR;
        public static final c hNS;
        public static final c hNT;
        public static final c hNU;
        public static final c hNV;
        public static final c hNW;
        public static final c hNX;
        private static final /* synthetic */ c[] hNY;
        public static final c hNa;
        public static final c hNb;
        public static final c hNc;
        public static final c hNd;
        public static final c hNe;
        public static final c hNf;
        public static final c hNg;
        public static final c hNh;
        public static final c hNi;
        public static final c hNj;
        public static final c hNk;
        public static final c hNl;
        public static final c hNm;
        public static final c hNn;
        public static final c hNo;
        public static final c hNp;
        public static final c hNq;
        public static final c hNr;
        public static final c hNx;
        public static final c hNy;
        public static final c hNz;
        public static final c vBP;
        public static final c vCO;
        public static final c vSe;
        public static final c vSh;
        public static final c vSi;
        public static final c vSj;
        public static final c vXQ;
        public static final c wLJ;
        public static final c wLW;
        public static final c wLX;
        public static final c wLY;
        public static final c wLZ;
        public static final c wMa;
        public static final c wMb;
        public static final c wMh;
        public static final c wMi;
        public static final c wMs;
        public static final c wMv;
        public static final c wMx;
        public static final c wMy;
        public static final c wMz;
        public static final c wlN;
        public static final c wlu;
        public static final c wsU;
        public static final c wsW;
        public static final c wsX;
        public static final c wtf;
        public static final c yPo;
        public static final c yPp;
        public static final c yVW;
        public static final c zeD;
        public static final c zeg;
        public static final c zeh;
        public static final c zen;
        public static final c zgj;
        public static final c zgk;

        static {
            AppMethodBeat.i(207871);
            c[] cVarArr = new c[TbsListener.ErrorCode.STARTDOWNLOAD_6];
            c cVar = new c("UNKNOWN", 0);
            hLt = cVar;
            cVarArr[0] = cVar;
            c cVar2 = new c("START_LIVE_VERIFY", 1);
            hLu = cVar2;
            cVarArr[1] = cVar2;
            c cVar3 = new c("LIVE_VERIFY_SUCCESS", 2);
            hLv = cVar3;
            cVarArr[2] = cVar3;
            c cVar4 = new c("START_FACE_VERIFY", 3);
            hLw = cVar4;
            cVarArr[3] = cVar4;
            c cVar5 = new c("LIVE_FACE_VERIFY_NEED_BIND_BANKCARD", 4);
            hLx = cVar5;
            cVarArr[4] = cVar5;
            c cVar6 = new c("BEFORE_LIVE", 5);
            hLy = cVar6;
            cVarArr[5] = cVar6;
            c cVar7 = new c("READY", 6);
            hLz = cVar7;
            cVarArr[6] = cVar7;
            c cVar8 = new c("READY_CGI", 7);
            hLA = cVar8;
            cVarArr[7] = cVar8;
            c cVar9 = new c("START_LIVE", 8);
            hLB = cVar9;
            cVarArr[8] = cVar9;
            c cVar10 = new c("CLOSE_LIVE", 9);
            hLC = cVar10;
            cVarArr[9] = cVar10;
            c cVar11 = new c("QUIT_LIVE", 10);
            hLD = cVar11;
            cVarArr[10] = cVar11;
            c cVar12 = new c("SWITCH_CAMERA", 11);
            hLE = cVar12;
            cVarArr[11] = cVar12;
            c cVar13 = new c("SHARE_LIVE", 12);
            hLF = cVar13;
            cVarArr[12] = cVar13;
            c cVar14 = new c("LIVE_SCREEN", 13);
            hLG = cVar14;
            cVarArr[13] = cVar14;
            c cVar15 = new c("LIVE_START_MIC_CGI", 14);
            hLH = cVar15;
            cVarArr[14] = cVar15;
            c cVar16 = new c("LIVE_START_MIC_SDK", 15);
            hLI = cVar16;
            cVarArr[15] = cVar16;
            c cVar17 = new c("LIVE_START_MIC_OTHER", 16);
            hLJ = cVar17;
            cVarArr[16] = cVar17;
            c cVar18 = new c("LIVE_START_MIC_PERMISSION_CLSOE", 17);
            hLK = cVar18;
            cVarArr[17] = cVar18;
            c cVar19 = new c("LIVE_STOP_MIC", 18);
            hLL = cVar19;
            cVarArr[18] = cVar19;
            c cVar20 = new c("LIVE_STOP_MIC_CGI", 19);
            hLM = cVar20;
            cVarArr[19] = cVar20;
            c cVar21 = new c("LIVE_STOP_MIC_OTHER", 20);
            hLN = cVar21;
            cVarArr[20] = cVar21;
            c cVar22 = new c("SHOW_MEMBERS_LIST", 21);
            hLO = cVar22;
            cVarArr[21] = cVar22;
            c cVar23 = new c("HIDE_MEMBERS_LIST", 22);
            hLP = cVar23;
            cVarArr[22] = cVar23;
            c cVar24 = new c("MINI_WINDOW", 23);
            hLQ = cVar24;
            cVarArr[23] = cVar24;
            c cVar25 = new c("MAXI_WINDOW", 24);
            hLR = cVar25;
            cVarArr[24] = cVar25;
            c cVar26 = new c("MINI_WINDOW_PERMISSION", 25);
            hLS = cVar26;
            cVarArr[25] = cVar26;
            c cVar27 = new c("MINI_WINDOW_REFUSE", 26);
            hLT = cVar27;
            cVarArr[26] = cVar27;
            c cVar28 = new c("MINI_WINDOW_CANCEL", 27);
            hLU = cVar28;
            cVarArr[27] = cVar28;
            c cVar29 = new c("LIVE_HAS_FINISHED", 28);
            hLV = cVar29;
            cVarArr[28] = cVar29;
            c cVar30 = new c("LIVE_CHANGE_FINISHED", 29);
            hLW = cVar30;
            cVarArr[29] = cVar30;
            c cVar31 = new c("DEBUG_ENTER", 30);
            hLX = cVar31;
            cVarArr[30] = cVar31;
            c cVar32 = new c("RENDERING", 31);
            hLY = cVar32;
            cVarArr[31] = cVar32;
            c cVar33 = new c("HIDE_SHARE_LIST", 32);
            hLZ = cVar33;
            cVarArr[32] = cVar33;
            c cVar34 = new c("POST_LIKE", 33);
            hMa = cVar34;
            cVarArr[33] = cVar34;
            c cVar35 = new c("POST_MSG", 34);
            hMb = cVar35;
            cVarArr[34] = cVar35;
            c cVar36 = new c("EXPOSE_LIVE", 35);
            hMc = cVar36;
            cVarArr[35] = cVar36;
            c cVar37 = new c("ENTERING_COMMENT", 36);
            hMd = cVar37;
            cVarArr[36] = cVar37;
            c cVar38 = new c("LIVE_STATUS_KICK_MEMBER", 37);
            hMe = cVar38;
            cVarArr[37] = cVar38;
            c cVar39 = new c("LIVE_STATUS_EXPOSE_MEMBER", 38);
            hMf = cVar39;
            cVarArr[38] = cVar39;
            c cVar40 = new c("LIVE_STATUS_SWITCH_VIDEO_MIC", 39);
            hMg = cVar40;
            cVarArr[39] = cVar40;
            c cVar41 = new c("LIVE_STATUS_SWITCH_AUDIO_MIC", 40);
            hMh = cVar41;
            cVarArr[40] = cVar41;
            c cVar42 = new c("LIVE_STATUS_VIDEO_MIC", 41);
            hMi = cVar42;
            cVarArr[41] = cVar42;
            c cVar43 = new c("LIVE_STATUS_CLOSE_MEMBER_PROFILE", 42);
            hMj = cVar43;
            cVarArr[42] = cVar43;
            c cVar44 = new c("LIVE_STATUS_OPEN_MEMBER_PROFILE", 43);
            hMk = cVar44;
            cVarArr[43] = cVar44;
            c cVar45 = new c("LIVE_STATUS_VISITOR_KICKED", 44);
            hMl = cVar45;
            cVarArr[44] = cVar45;
            c cVar46 = new c("LIVE_STATUS_VISITOR_PRIVATE_PERMISSION", 45);
            hMm = cVar46;
            cVarArr[45] = cVar46;
            c cVar47 = new c("LIVE_STATUS_RECONNECT", 46);
            hMn = cVar47;
            cVarArr[46] = cVar47;
            c cVar48 = new c("LIVE_STATUS_DISCONNECT", 47);
            hMo = cVar48;
            cVarArr[47] = cVar48;
            c cVar49 = new c("LIVE_STATUS_CONNECT_SUCC", 48);
            hMp = cVar49;
            cVarArr[48] = cVar49;
            c cVar50 = new c("LIVE_STATUS_ANCHOR_EXCEPTION", 49);
            hMq = cVar50;
            cVarArr[49] = cVar50;
            c cVar51 = new c("LIVE_START_LIVE_FAILED", 50);
            hMr = cVar51;
            cVarArr[50] = cVar51;
            c cVar52 = new c("LIVE_START_LIVE_SUCCESS", 51);
            hMs = cVar52;
            cVarArr[51] = cVar52;
            c cVar53 = new c("LIVE_READY_CANCEL_COUNTER", 52);
            hMt = cVar53;
            cVarArr[52] = cVar53;
            c cVar54 = new c("LIVE_STATUS_ANCHOR_RECOVERY", 53);
            hMu = cVar54;
            cVarArr[53] = cVar54;
            c cVar55 = new c("LIVE_STATUS_EXCEPTION", 54);
            hMv = cVar55;
            cVarArr[54] = cVar55;
            c cVar56 = new c("LIVE_STATUS_JOIN_LIVE", 55);
            hMw = cVar56;
            cVarArr[55] = cVar56;
            c cVar57 = new c("LIVE_STATUS_CREATE_LIVE", 56);
            hMx = cVar57;
            cVarArr[56] = cVar57;
            c cVar58 = new c("LIVE_STATUS_FIRST_I_FRAME", 57);
            hMy = cVar58;
            cVarArr[57] = cVar58;
            c cVar59 = new c("VISITOR_NOT_BIND_MOBILE", 58);
            hMz = cVar59;
            cVarArr[58] = cVar59;
            c cVar60 = new c("VISITOR_COMMENT_ENTERING_OP", 59);
            hMA = cVar60;
            cVarArr[59] = cVar60;
            c cVar61 = new c("LIVE_HAPPEN_VOIP_EVENT", 60);
            hMB = cVar61;
            cVarArr[60] = cVar61;
            c cVar62 = new c("LIVE_ORIENTATION_CHANGE", 61);
            hMC = cVar62;
            cVarArr[61] = cVar62;
            c cVar63 = new c("LIVE_STATUS_COMMENT_LAYOUT_UPDATE", 62);
            hMD = cVar63;
            cVarArr[62] = cVar63;
            c cVar64 = new c("LIVE_STATUS_RESOLUTION", 63);
            hME = cVar64;
            cVarArr[63] = cVar64;
            c cVar65 = new c("LIVE_MIRROR_ACTION_EVENT", 64);
            hMF = cVar65;
            cVarArr[64] = cVar65;
            c cVar66 = new c("LIVE_EVENT_SHOW_GIFT_PANEL", 65);
            hMG = cVar66;
            cVarArr[65] = cVar66;
            c cVar67 = new c("LIVE_EVENT_HIDE_GIFT_PANEL", 66);
            hMH = cVar67;
            cVarArr[66] = cVar67;
            c cVar68 = new c("LIVE_EVENT_PREVIEW_GIFT", 67);
            hMI = cVar68;
            cVarArr[67] = cVar68;
            c cVar69 = new c("LIVE_EVENT_SEND_GIFT", 68);
            hMJ = cVar69;
            cVarArr[68] = cVar69;
            c cVar70 = new c("LIVE_EVENT_SHOW_FULL_SCREEN_GIFT", 69);
            hMK = cVar70;
            cVarArr[69] = cVar70;
            c cVar71 = new c("LIVE_EVENT_HIDE_FULL_SCREEN_GIFT", 70);
            hML = cVar71;
            cVarArr[70] = cVar71;
            c cVar72 = new c("LIVE_EVENT_GIFT_UPDATE_WECOIN", 71);
            hMM = cVar72;
            cVarArr[71] = cVar72;
            c cVar73 = new c("LIVE_EVENT_GIFT_SHOW_SEND_BTN", 72);
            hMN = cVar73;
            cVarArr[72] = cVar73;
            c cVar74 = new c("LIVE_EVENT_GIFT_HIDE_SEND_BTN", 73);
            hMO = cVar74;
            cVarArr[73] = cVar74;
            c cVar75 = new c("FINDER_LIVE_MIC_PANEL_DISPLAY", 74);
            hMP = cVar75;
            cVarArr[74] = cVar75;
            c cVar76 = new c("FINDER_LIVE_LINK_MIC_APPLY", 75);
            hMQ = cVar76;
            cVarArr[75] = cVar76;
            c cVar77 = new c("FINDER_LIVE_LINK_MIC_ACCEPT", 76);
            hMR = cVar77;
            cVarArr[76] = cVar77;
            c cVar78 = new c("FINDER_LIVE_LINK_MIC_CLOSE", 77);
            hMS = cVar78;
            cVarArr[77] = cVar78;
            c cVar79 = new c("FINDER_LIVE_MEMBERS_LOADING", 78);
            hMU = cVar79;
            cVarArr[78] = cVar79;
            c cVar80 = new c("FINDER_LIVE_MEMBERS_AUTO_REFRESH", 79);
            hMV = cVar80;
            cVarArr[79] = cVar80;
            c cVar81 = new c("FINDER_LIVE_APPLY_LINK_EXPOSED", 80);
            hMW = cVar81;
            cVarArr[80] = cVar81;
            c cVar82 = new c("FINDER_LIVE_LINK_DISPLAY_STATUS_PANEL", 81);
            hMX = cVar82;
            cVarArr[81] = cVar82;
            c cVar83 = new c("FINDER_LIVE_LINK_DISPLAY_NOTIFY_PANEL", 82);
            hMY = cVar83;
            cVarArr[82] = cVar83;
            c cVar84 = new c("FINDER_LIVE_SHOPPING_LIST_SHOW", 83);
            hMZ = cVar84;
            cVarArr[83] = cVar84;
            c cVar85 = new c("FINDER_LIVE_SHOPPING_LIST_HIDE", 84);
            hNa = cVar85;
            cVarArr[84] = cVar85;
            c cVar86 = new c("FINDER_LIVE_SHOPPING_PROMOTING", 85);
            hNb = cVar86;
            cVarArr[85] = cVar86;
            c cVar87 = new c("FINDER_LIVE_SHOPPING_REFRESH", 86);
            hNc = cVar87;
            cVarArr[86] = cVar87;
            c cVar88 = new c("FINDER_LIVE_INIT_SHOPPING_PLUGIN", 87);
            vBP = cVar88;
            cVarArr[87] = cVar88;
            c cVar89 = new c("FINDER_LIVE_COMMENT_MOVE", 88);
            hNd = cVar89;
            cVarArr[88] = cVar89;
            c cVar90 = new c("FINDER_LIVE_FACE_VERIFY", 89);
            hNe = cVar90;
            cVarArr[89] = cVar90;
            c cVar91 = new c("FINDER_LIVE_LINK_INVITE", 90);
            hNf = cVar91;
            cVarArr[90] = cVar91;
            c cVar92 = new c("FINDER_LIVE_FORCE_QUIT", 91);
            hNg = cVar92;
            cVarArr[91] = cVar92;
            c cVar93 = new c("FINDER_LIVE_UPDATE_LIVE_MSG", 92);
            hNh = cVar93;
            cVarArr[92] = cVar93;
            c cVar94 = new c("FINDER_LIVE_AUTO_INPUT_COMMENT", 93);
            hNi = cVar94;
            cVarArr[93] = cVar94;
            c cVar95 = new c("FINDER_LIVE_COMMENT_REAL_NAME", 94);
            hNj = cVar95;
            cVarArr[94] = cVar95;
            c cVar96 = new c("FINDER_LIVE_COMMENT_BACKOFF", 95);
            hNk = cVar96;
            cVarArr[95] = cVar96;
            c cVar97 = new c("FINDER_LIVE_CLEAR_SCREEN", 96);
            hNl = cVar97;
            cVarArr[96] = cVar97;
            c cVar98 = new c("FINDER_LIVE_IDLE", 97);
            hNm = cVar98;
            cVarArr[97] = cVar98;
            c cVar99 = new c("FINDER_LIVE_MORE_ACTION_SHOW", 98);
            hNn = cVar99;
            cVarArr[98] = cVar99;
            c cVar100 = new c("FINDER_LIVE_MORE_ACTION_HIDE", 99);
            hNo = cVar100;
            cVarArr[99] = cVar100;
            c cVar101 = new c("FINDER_LIVE_STATISTC_EVENT", 100);
            hNp = cVar101;
            cVarArr[100] = cVar101;
            c cVar102 = new c("FINDER_LIVE_TOP_COMMENNT", 101);
            hNq = cVar102;
            cVarArr[101] = cVar102;
            c cVar103 = new c("FINDER_LIVE_MSG_ACTION_SHEET", 102);
            hNr = cVar103;
            cVarArr[102] = cVar103;
            c cVar104 = new c("FINDER_LIVE_SHOW_CAMERA_OPT_SHEET", 103);
            hNx = cVar104;
            cVarArr[103] = cVar104;
            c cVar105 = new c("FINDER_LIVE_HIDE_CAMERA_OPT_SHEET", 104);
            hNy = cVar105;
            cVarArr[104] = cVar105;
            c cVar106 = new c("FINDER_LIVE_CREATE_ERROR_PAGE", 105);
            hNz = cVar106;
            cVarArr[105] = cVar106;
            c cVar107 = new c("FINDER_LIVE_CREATE_LOTTERY_SUCCESS", 106);
            hNA = cVar107;
            cVarArr[106] = cVar107;
            c cVar108 = new c("FINDER_LIVE_CANCEL_LOTTERY_SUCCESS", 107);
            hNB = cVar108;
            cVarArr[107] = cVar108;
            c cVar109 = new c("FINDER_LIVE_LOTTERY_BUBBLE_SHOW", 108);
            hNC = cVar109;
            cVarArr[108] = cVar109;
            c cVar110 = new c("FINDER_LIVE_LOTTERY_BUBBLE_HIDE", 109);
            hND = cVar110;
            cVarArr[109] = cVar110;
            c cVar111 = new c("FINDER_LIVE_LOTTERY_CARD_SHOW", 110);
            hNE = cVar111;
            cVarArr[110] = cVar111;
            c cVar112 = new c("FINDER_LIVE_LOTTERY_CARD_HIDE", 111);
            hNF = cVar112;
            cVarArr[111] = cVar112;
            c cVar113 = new c("FINDER_LIVE_LOTTERY_UPDATE", 112);
            hNG = cVar113;
            cVarArr[112] = cVar113;
            c cVar114 = new c("FINDER_LIVE_LOTTERY_UPDATE_COUNTDOWN", 113);
            hNH = cVar114;
            cVarArr[113] = cVar114;
            c cVar115 = new c("FINDER_LIVE_LIKE_SHAKE", 114);
            hNI = cVar115;
            cVarArr[114] = cVar115;
            c cVar116 = new c("FINDER_LIVE_SHOW_ALERT_DIALOG", 115);
            hNJ = cVar116;
            cVarArr[115] = cVar116;
            c cVar117 = new c("FINDER_LIVE_POST_HL_LIKE", 116);
            hNK = cVar117;
            cVarArr[116] = cVar117;
            c cVar118 = new c("FINDER_LIVE_LINK_MIC_VISITOR_REQUEST", 117);
            hNL = cVar118;
            cVarArr[117] = cVar118;
            c cVar119 = new c("FINDER_LIVE_LINK_MIC_SHOW_APPLY_LIST", 118);
            hNM = cVar119;
            cVarArr[118] = cVar119;
            c cVar120 = new c("FINDER_LIVE_LINK_MIC_HIDE_APPLY_LIST", 119);
            hNN = cVar120;
            cVarArr[119] = cVar120;
            c cVar121 = new c("FINDER_LIVE_LINK_MIC_ANCHOR_ACCEPT", 120);
            hNO = cVar121;
            cVarArr[120] = cVar121;
            c cVar122 = new c("FINDER_LIVE_LINK_MIC_HANGUP_LINK", 121);
            hNP = cVar122;
            cVarArr[121] = cVar122;
            c cVar123 = new c("FINDER_LIVE_LINK_MIC_ADD_BOTTOM_BAR", 122);
            hNQ = cVar123;
            cVarArr[122] = cVar123;
            c cVar124 = new c("FINDER_LIVE_LINK_MIC_REMOVE_BOTTOM_BAR", 123);
            hNR = cVar124;
            cVarArr[123] = cVar124;
            c cVar125 = new c("FINDER_LIVE_LINK_MIC_ANCHOR_SETTING", 124);
            hNS = cVar125;
            cVarArr[124] = cVar125;
            c cVar126 = new c("FINDER_LIVE_LINK_MIC_SHOW_APPLY_LICENSE", 125);
            hNT = cVar126;
            cVarArr[125] = cVar126;
            c cVar127 = new c("FINDER_LIVE_LINK_MIC_HIDE_APPLY_LICENSE", 126);
            hNU = cVar127;
            cVarArr[126] = cVar127;
            c cVar128 = new c("FINDER_LIVE_LINK_MIC_CHECKED", TPOptionalID.OPTION_ID_BEFORE_BOOL_ENABLE_AUDIO_PASSTHROUGH);
            hNV = cVar128;
            cVarArr[127] = cVar128;
            c cVar129 = new c("FINDER_LIVE_LINK_MIC_APPLY_PK", 128);
            vCO = cVar129;
            cVarArr[128] = cVar129;
            c cVar130 = new c("FINDER_LIVE_LINK_MIC_ACCEPT_PK", 129);
            vSe = cVar130;
            cVarArr[129] = cVar130;
            c cVar131 = new c("FINDER_LIVE_SHOW_EXPLAIN_WECOIN_HOT", 130);
            hNW = cVar131;
            cVarArr[130] = cVar131;
            c cVar132 = new c("FINDER_LIVE_HIDE_EXPLAIN_WECOIN_HOT", TPCodecParamers.TP_PROFILE_MPEG2_AAC_HE);
            hNX = cVar132;
            cVarArr[131] = cVar132;
            c cVar133 = new c("FINDER_LIVE_ANCHOR_LUCKY_MONEY_BUBBLE_SHOW", 132);
            vSh = cVar133;
            cVarArr[132] = cVar133;
            c cVar134 = new c("FINDER_LIVE_ANCHOR_LUCKY_MONEY_BUBBLE_HIDE", 133);
            vSi = cVar134;
            cVarArr[133] = cVar134;
            c cVar135 = new c("FINDER_LIVE_RECEIVE_LUCKY_MONEY", g.CTRL_INDEX);
            vSj = cVar135;
            cVarArr[134] = cVar135;
            c cVar136 = new c("FINDER_LIVE_SHOW_VISITOR_ROLE_CHOOSER", com.tencent.mm.plugin.appbrand.jsapi.k.c.CTRL_INDEX);
            vXQ = cVar136;
            cVarArr[135] = cVar136;
            c cVar137 = new c("FINDER_LIVE_SHOW_BOTTOM_TIP_PANEL", r.CTRL_INDEX);
            wlu = cVar137;
            cVarArr[136] = cVar137;
            c cVar138 = new c("FESTIVAL_FINDER_LIVE_ENTER_POST_WISH", 137);
            wlN = cVar138;
            cVarArr[137] = cVar138;
            c cVar139 = new c("FESTIVAL_FINDER_LIVE_SHOW_POST_PANEL", 138);
            wsU = cVar139;
            cVarArr[138] = cVar139;
            c cVar140 = new c("FESTIVAL_FINDER_LIVE_RESTORE_INITIAL", com.tencent.mm.plugin.appbrand.jsapi.p.b.CTRL_INDEX);
            wsW = cVar140;
            cVarArr[139] = cVar140;
            c cVar141 = new c("FESTIVAL_FINDER_LIVE_SHOW_WISH_CARD", 140);
            wsX = cVar141;
            cVarArr[140] = cVar141;
            c cVar142 = new c("FESTIVAL_FINDER_LIVE_SET_STATE", 141);
            wtf = cVar142;
            cVarArr[141] = cVar142;
            c cVar143 = new c("FESTIVAL_FINDER_LIVE_POST_WISH_PROCESS_FINISH", TbsListener.ErrorCode.NEEDDOWNLOAD_3);
            wLJ = cVar143;
            cVarArr[142] = cVar143;
            c cVar144 = new c("FESTIVAL_FINDER_LIVE_POST_WISH_PANEL_CANCEL", TbsListener.ErrorCode.NEEDDOWNLOAD_4);
            wLW = cVar144;
            cVarArr[143] = cVar144;
            c cVar145 = new c("FESTIVAL_FINDER_LIVE_POST_WISH_POSTED_AFTER_ACTION", 144);
            wLX = cVar145;
            cVarArr[144] = cVar145;
            c cVar146 = new c("FESTIVAL_FINDER_LIVE_POST_WISH_POSTED_AFTER_ACTION_FINISH", 145);
            wLY = cVar146;
            cVarArr[145] = cVar146;
            c cVar147 = new c("FESTIVAL_FINDER_LIVE_CANVAS_VIEWPORT_READY", 146);
            wLZ = cVar147;
            cVarArr[146] = cVar147;
            c cVar148 = new c("FESTIVAL_FINDER_LIVE_CANVAS_DATA_READY", TbsListener.ErrorCode.NEEDDOWNLOAD_8);
            wMa = cVar148;
            cVarArr[147] = cVar148;
            c cVar149 = new c("FESTIVAL_FINDER_LIVE_SHOW_MY_NEW_WISH_NORTH_STAR", 148);
            wMb = cVar149;
            cVarArr[148] = cVar149;
            c cVar150 = new c("FESTIVAL_FINDER_LIVE_SHOW_MY_NEW_WISH_AVATAR", 149);
            wMh = cVar150;
            cVarArr[149] = cVar150;
            c cVar151 = new c("FESTIVAL_FINDER_LIVE_INSERT_MY_NEW_WISH_IN_DANMAKU", 150);
            wMi = cVar151;
            cVarArr[150] = cVar151;
            c cVar152 = new c("FESTIVAL_FINDER_LIVE_CANVAS_TRANSFORM_EVENT_FOR_MY_NEW_WISH", 151);
            wMs = cVar152;
            cVarArr[151] = cVar152;
            c cVar153 = new c("FESTIVAL_FINDER_LIVE_MY_WISH_DELETED", 152);
            wMv = cVar153;
            cVarArr[152] = cVar153;
            c cVar154 = new c("FESTIVAL_FINDER_LIVE_CANVAS_CLICK_EVENT", 153);
            wMx = cVar154;
            cVarArr[153] = cVar154;
            c cVar155 = new c("FESTIVAL_FINDER_LIVE_MINI_WINDOW", 154);
            wMy = cVar155;
            cVarArr[154] = cVar155;
            c cVar156 = new c("FESTIVAL_FINDER_LIVE_POST_WISH_NEED_REAL_NAME", 155);
            wMz = cVar156;
            cVarArr[155] = cVar156;
            c cVar157 = new c("FESTIVAL_FINDER_LIVE_CHECK_SHOW_FU_BAG", 156);
            yPo = cVar157;
            cVarArr[156] = cVar157;
            c cVar158 = new c("FESTIVAL_FINDER_LIVE_FAIRY_WAND_TOUCH_START", 157);
            yPp = cVar158;
            cVarArr[157] = cVar158;
            c cVar159 = new c("FESTIVAL_FINDER_LIVE_FAIRY_WAND_TOUCH_END", 158);
            yVW = cVar159;
            cVarArr[158] = cVar159;
            c cVar160 = new c("FESTIVAL_FINDER_LIVE_FAIRY_WAND_DISAPPEAR_START", JsApiGetBackgroundAudioState.CTRL_INDEX);
            zeg = cVar160;
            cVarArr[159] = cVar160;
            c cVar161 = new c("FESTIVAL_FINDER_LIVE_FAIRY_WAND_DISAPPEAR_END", 160);
            zeh = cVar161;
            cVarArr[160] = cVar161;
            c cVar162 = new c("FESTIVAL_FINDER_LIVE_FAIRY_WAND_SEND_TO_FRIEND", 161);
            zen = cVar162;
            cVarArr[161] = cVar162;
            c cVar163 = new c("FESTIVAL_FINDER_LIVE_FAIRY_WAND_SHARE_SNS", TbsListener.ErrorCode.STARTDOWNLOAD_3);
            zeD = cVar163;
            cVarArr[162] = cVar163;
            c cVar164 = new c("FESTIVAL_FINDER_LIVE_ON_FU_BAG_VISIBILITY_CHANGED", TbsListener.ErrorCode.STARTDOWNLOAD_4);
            zgj = cVar164;
            cVarArr[163] = cVar164;
            c cVar165 = new c("FESTIVAL_FINDER_LIVE_ON_WISH_BUTTON_LAYOUT_CHANGED", TbsListener.ErrorCode.STARTDOWNLOAD_5);
            zgk = cVar165;
            cVarArr[164] = cVar165;
            hNY = cVarArr;
            AppMethodBeat.o(207871);
        }

        public static c valueOf(String str) {
            AppMethodBeat.i(207873);
            c cVar = (c) Enum.valueOf(c.class, str);
            AppMethodBeat.o(207873);
            return cVar;
        }

        public static c[] values() {
            AppMethodBeat.i(207872);
            c[] cVarArr = (c[]) hNY.clone();
            AppMethodBeat.o(207872);
            return cVarArr;
        }

        private c(String str, int i2) {
            super(str, i2);
        }
    }

    public static final class a {
        static final /* synthetic */ a hLs = new a();

        static {
            AppMethodBeat.i(207869);
            AppMethodBeat.o(207869);
        }

        private a() {
        }
    }

    /* renamed from: com.tencent.mm.live.c.b$b */
    public static final class C0376b {
        public static /* synthetic */ void a(b bVar, c cVar) {
            AppMethodBeat.i(207870);
            bVar.statusChange(cVar, null);
            AppMethodBeat.o(207870);
        }
    }
}
