package com.tencent.mm.plugin.appbrand.jsapi;

import com.tencent.luggage.xweb_ext.extendplugin.component.live.livepusher.r;
import com.tencent.matrix.trace.core.AppMethodBeat;
import com.tencent.mm.plugin.appbrand.ad.a.i;
import com.tencent.mm.plugin.appbrand.app.j;
import com.tencent.mm.plugin.appbrand.bd;
import com.tencent.mm.plugin.appbrand.jsapi.appdownload.JsApiAddDownloadTask;
import com.tencent.mm.plugin.appbrand.jsapi.appdownload.JsApiAddDownloadTaskForNative;
import com.tencent.mm.plugin.appbrand.jsapi.appdownload.JsApiAddDownloadTaskStraight;
import com.tencent.mm.plugin.appbrand.jsapi.appdownload.JsApiCancelDownloadTask;
import com.tencent.mm.plugin.appbrand.jsapi.appdownload.JsApiCancelDownloadTaskForNative;
import com.tencent.mm.plugin.appbrand.jsapi.appdownload.JsApiGetInstallState;
import com.tencent.mm.plugin.appbrand.jsapi.appdownload.JsApiGetInstallStateForNative;
import com.tencent.mm.plugin.appbrand.jsapi.appdownload.JsApiInstallDownloadTask;
import com.tencent.mm.plugin.appbrand.jsapi.appdownload.JsApiInstallDownloadTaskForNative;
import com.tencent.mm.plugin.appbrand.jsapi.appdownload.JsApiJumpDownloaderWidgetForNative;
import com.tencent.mm.plugin.appbrand.jsapi.appdownload.JsApiLaunchApplicationForNative;
import com.tencent.mm.plugin.appbrand.jsapi.appdownload.JsApiPauseDownloadTask;
import com.tencent.mm.plugin.appbrand.jsapi.appdownload.JsApiPauseDownloadTaskForNative;
import com.tencent.mm.plugin.appbrand.jsapi.appdownload.JsApiQueryDownloadTask;
import com.tencent.mm.plugin.appbrand.jsapi.appdownload.JsApiQueryDownloadTaskForNative;
import com.tencent.mm.plugin.appbrand.jsapi.appdownload.JsApiResumeDownloadTaskForNative;
import com.tencent.mm.plugin.appbrand.jsapi.audio.JsApiGetBackgroundAudioState;
import com.tencent.mm.plugin.appbrand.jsapi.audio.JsApiGetMusicPlayerState;
import com.tencent.mm.plugin.appbrand.jsapi.audio.JsApiOperateMusicPlayer;
import com.tencent.mm.plugin.appbrand.jsapi.audio.JsApiPausePlayVoice;
import com.tencent.mm.plugin.appbrand.jsapi.audio.JsApiSetBackgroundAudioStateWC;
import com.tencent.mm.plugin.appbrand.jsapi.audio.JsApiStartPlayVoice;
import com.tencent.mm.plugin.appbrand.jsapi.audio.JsApiStartRecordVoice;
import com.tencent.mm.plugin.appbrand.jsapi.audio.JsApiStopPlayVoice;
import com.tencent.mm.plugin.appbrand.jsapi.audio.JsApiStopRecordVoice;
import com.tencent.mm.plugin.appbrand.jsapi.auth.JsApiAuthorize;
import com.tencent.mm.plugin.appbrand.jsapi.auth.JsApiLogin;
import com.tencent.mm.plugin.appbrand.jsapi.auth.JsApiOperateWXData;
import com.tencent.mm.plugin.appbrand.jsapi.backgroundfetch.JsApiSetBackgroundFetchToken;
import com.tencent.mm.plugin.appbrand.jsapi.backgroundfetch.JsApiTriggerBackgroundFetch;
import com.tencent.mm.plugin.appbrand.jsapi.bio.face.JsApiCheckIsSupportFaceDetect;
import com.tencent.mm.plugin.appbrand.jsapi.bio.soter.JsApiCheckBioEnrollment;
import com.tencent.mm.plugin.appbrand.jsapi.bio.soter.JsApiCheckIsSupportSoterAuthentication;
import com.tencent.mm.plugin.appbrand.jsapi.bizvideochannel.JsApiHandleMpChannelAction;
import com.tencent.mm.plugin.appbrand.jsapi.bizvideochannel.JsApiOpenWebViewUseFastLoad;
import com.tencent.mm.plugin.appbrand.jsapi.camera.AppBrandCameraView;
import com.tencent.mm.plugin.appbrand.jsapi.camera.SameLayerCameraView;
import com.tencent.mm.plugin.appbrand.jsapi.contact.JsApiChooseWeChatContact;
import com.tencent.mm.plugin.appbrand.jsapi.fakenative.JsApiRemoveSplashScreenshot;
import com.tencent.mm.plugin.appbrand.jsapi.file.ap;
import com.tencent.mm.plugin.appbrand.jsapi.file.aq;
import com.tencent.mm.plugin.appbrand.jsapi.file.ar;
import com.tencent.mm.plugin.appbrand.jsapi.file.as;
import com.tencent.mm.plugin.appbrand.jsapi.file.v;
import com.tencent.mm.plugin.appbrand.jsapi.finder.JsApiDeleteFinderDataItem;
import com.tencent.mm.plugin.appbrand.jsapi.finder.JsApiFetchSendingAndFailProfileFeed;
import com.tencent.mm.plugin.appbrand.jsapi.finder.JsApiFinderEndorsementFinished;
import com.tencent.mm.plugin.appbrand.jsapi.finder.JsApiGetFinderAccount;
import com.tencent.mm.plugin.appbrand.jsapi.finder.JsApiPostFinderDataItem;
import com.tencent.mm.plugin.appbrand.jsapi.finder.JsApiResendProfileFeed;
import com.tencent.mm.plugin.appbrand.jsapi.i.p;
import com.tencent.mm.plugin.appbrand.jsapi.i.u;
import com.tencent.mm.plugin.appbrand.jsapi.k.ac;
import com.tencent.mm.plugin.appbrand.jsapi.k.y;
import com.tencent.mm.plugin.appbrand.jsapi.lab.JsApiGetLabInfo;
import com.tencent.mm.plugin.appbrand.jsapi.lab.JsApiSetLabInfo;
import com.tencent.mm.plugin.appbrand.jsapi.media.JsApiChooseImage;
import com.tencent.mm.plugin.appbrand.jsapi.media.JsApiChooseMedia;
import com.tencent.mm.plugin.appbrand.jsapi.media.JsApiChooseMultiMedia;
import com.tencent.mm.plugin.appbrand.jsapi.media.JsApiUploadEncryptedFileToCDN;
import com.tencent.mm.plugin.appbrand.jsapi.media.k;
import com.tencent.mm.plugin.appbrand.jsapi.media.l;
import com.tencent.mm.plugin.appbrand.jsapi.media.m;
import com.tencent.mm.plugin.appbrand.jsapi.miniprogram_navigator.JsApiNavigateToDevMiniProgram;
import com.tencent.mm.plugin.appbrand.jsapi.msgsubscription.JsApiRequestSubscribeMessage;
import com.tencent.mm.plugin.appbrand.jsapi.nfc.hce.HCEService;
import com.tencent.mm.plugin.appbrand.jsapi.nfc.rw.logic.c;
import com.tencent.mm.plugin.appbrand.jsapi.p.aa;
import com.tencent.mm.plugin.appbrand.jsapi.p.ad;
import com.tencent.mm.plugin.appbrand.jsapi.p.ae;
import com.tencent.mm.plugin.appbrand.jsapi.p.af;
import com.tencent.mm.plugin.appbrand.jsapi.p.ag;
import com.tencent.mm.plugin.appbrand.jsapi.p.ah;
import com.tencent.mm.plugin.appbrand.jsapi.p.ai;
import com.tencent.mm.plugin.appbrand.jsapi.p.am;
import com.tencent.mm.plugin.appbrand.jsapi.p.an;
import com.tencent.mm.plugin.appbrand.jsapi.p.ao;
import com.tencent.mm.plugin.appbrand.jsapi.p.s;
import com.tencent.mm.plugin.appbrand.jsapi.p.w;
import com.tencent.mm.plugin.appbrand.jsapi.p.x;
import com.tencent.mm.plugin.appbrand.jsapi.p.z;
import com.tencent.mm.plugin.appbrand.jsapi.r.e;
import com.tencent.mm.plugin.appbrand.jsapi.rencentusage.JsApiGetRecentUsageList;
import com.tencent.mm.plugin.appbrand.jsapi.rencentusage.JsApiOperateRecentUsageList;
import com.tencent.mm.plugin.appbrand.jsapi.scanner.JsApiScanCode;
import com.tencent.mm.plugin.appbrand.jsapi.scanner.JsApiScanItem;
import com.tencent.mm.plugin.appbrand.jsapi.share.JsApiShowUpdatableMessageSubscribeButton;
import com.tencent.mm.plugin.appbrand.jsapi.storage.f;
import com.tencent.mm.plugin.appbrand.jsapi.video.b;
import com.tencent.mm.plugin.appbrand.luggage.b.g;
import com.tencent.mm.plugin.appbrand.luggage.b.n;
import com.tencent.mm.plugin.appbrand.platform.window.h;
import com.tencent.mm.plugin.appbrand.s.o;
import com.tencent.mm.plugin.appbrand.utils.ab;
import com.tencent.mm.plugin.appbrand.utils.aj;
import com.tencent.mm.plugin.appbrand.utils.ak;
import com.tencent.mm.plugin.appbrand.utils.al;
import com.tencent.mm.plugin.appbrand.widget.input.panel.e;
import com.tencent.mm.plugin.appbrand.x.a;
import com.tencent.mm.plugin.appbrand.xweb_ext.a.q;
import com.tencent.mm.protocal.d;
import com.tencent.mm.sdk.platformtools.BuildInfo;
import com.tencent.mm.sdk.platformtools.Log;
import com.tencent.mm.sdk.platformtools.Util;
import com.tencent.mm.sdk.platformtools.WeChatEnvironment;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

public final class t {
    private static final boolean lxT = (BuildInfo.IS_FLAVOR_RED || BuildInfo.IS_FLAVOR_PURPLE || !d.KyP || WeChatEnvironment.hasDebugger());
    private long lxU;
    private long lxV;
    private final Map<String, p> lxW = new HashMap<String, p>() {
        /* class com.tencent.mm.plugin.appbrand.jsapi.t.AnonymousClass1 */

        public final String toString() {
            AppMethodBeat.i(45420);
            String format = String.format(Locale.ENGLISH, "ServiceAPIs[%d]", Integer.valueOf(size()));
            AppMethodBeat.o(45420);
            return format;
        }
    };
    private final Map<String, p> lxX = new HashMap<String, p>() {
        /* class com.tencent.mm.plugin.appbrand.jsapi.t.AnonymousClass2 */

        public final String toString() {
            AppMethodBeat.i(45421);
            String format = String.format(Locale.ENGLISH, "PageAPIs[%d]", Integer.valueOf(size()));
            AppMethodBeat.o(45421);
            return format;
        }
    };

    static {
        AppMethodBeat.i(45430);
        a.bUd();
        b.init();
        AppBrandCameraView.bFJ();
        SameLayerCameraView.bFJ();
        de.bEv();
        j.UJ("com.tencent.mm.plugin.soter.PluginSoter");
        j.UJ("com.tencent.mm.plugin.facedetect.PluginFace");
        c.a aVar = c.miO;
        c.a.b(com.tencent.mm.plugin.appbrand.t.b.INSTANCE);
        e.a(h.nEx);
        r.a(q.oHw);
        com.tencent.luggage.a.e.a(o.class, new com.tencent.mm.plugin.appbrand.luggage.c.c());
        com.tencent.luggage.a.e.a(com.tencent.mm.plugin.appbrand.utils.b.a.class, new u());
        com.tencent.luggage.a.e.a(com.tencent.luggage.c.a.a.class, new g());
        com.tencent.luggage.a.e.a(com.tencent.mm.plugin.appbrand.widget.input.a.b.class, com.tencent.mm.plugin.appbrand.luggage.b.d.nae);
        com.tencent.luggage.a.e.a(e.b.class, new com.tencent.mm.plugin.appbrand.luggage.b.e());
        com.tencent.luggage.a.e.a(com.tencent.mm.plugin.appbrand.jsapi.y.a.class, new com.tencent.mm.plugin.appbrand.jsapi.y.j());
        com.tencent.luggage.a.e.a(ag.class, new com.tencent.mm.plugin.appbrand.luggage.b.a());
        com.tencent.luggage.a.e.a(com.tencent.mm.plugin.appbrand.jsapi.ag.e.a.b.class, new ab());
        com.tencent.luggage.a.e.a(com.tencent.mm.plugin.appbrand.jsapi.k.a.c.class, new com.tencent.mm.plugin.appbrand.luggage.b.o());
        com.tencent.luggage.a.e.a(com.tencent.mm.plugin.appbrand.widget.b.b.class, new n());
        com.tencent.luggage.a.e.a(com.tencent.mm.plugin.appbrand.jsapi.ag.e.a.c.class, new com.tencent.mm.plugin.appbrand.report.n());
        com.tencent.luggage.a.e.a(ai.class, new al());
        com.tencent.luggage.a.e.a(com.tencent.mm.plugin.appbrand.jsapi.u.a.class, ak.ohK);
        com.tencent.luggage.a.e.a(com.tencent.mm.plugin.appbrand.jsapi.camera.e.class, new com.tencent.mm.plugin.appbrand.jsapi.ag.a.b());
        com.tencent.luggage.a.e.a(com.tencent.mm.plugin.appbrand.jsapi.nfc.c.class, aj.ohH);
        AppMethodBeat.o(45430);
    }

    private t() {
        AppMethodBeat.i(45422);
        AppMethodBeat.o(45422);
    }

    public static Map<String, p> bEk() {
        AppMethodBeat.i(45423);
        t tVar = new t();
        tVar.lxU = Util.currentTicks();
        tVar.b(new com.tencent.mm.plugin.appbrand.ad.a.h());
        tVar.b(new com.tencent.mm.plugin.appbrand.ad.a.g());
        tVar.b(new com.tencent.mm.plugin.appbrand.ad.a.a());
        tVar.b(new com.tencent.mm.plugin.appbrand.ad.a.j());
        tVar.b(new i());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.storage.a());
        tVar.b(new f());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.storage.n());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.storage.b());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.storage.i());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.storage.o());
        tVar.b(new JsApiLogin());
        tVar.b(new JsApiAuthorize());
        tVar.b(new JsApiOperateWXData());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.auth.j());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.p.ab());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.p.j());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.p.r());
        tVar.b(new s());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.p.i());
        tVar.b(new ci());
        tVar.b(new JsApiChooseImage());
        tVar.b(new l());
        tVar.b(new m());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.media.h());
        tVar.b(new k());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.media.i());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.media.g());
        tVar.b(new JsApiStartRecordVoice());
        tVar.b(new JsApiStopRecordVoice());
        tVar.b(new JsApiStartPlayVoice());
        tVar.b(new JsApiPausePlayVoice());
        tVar.b(new JsApiStopPlayVoice());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.i.n());
        tVar.b(new p());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.z.g());
        tVar.b(new JsApiGetMusicPlayerState());
        tVar.b(new JsApiOperateMusicPlayer());
        tVar.b(new JsApiScanCode());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.scanner.a());
        tVar.b(new JsApiScanItem());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.pay.n());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.pay.l());
        tVar.b(new bt());
        tVar.b(new bu());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.w.d());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.pay.s());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.pay.b());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.contact.c());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.contact.g());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.p.al());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.pay.e());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.pay.h());
        tVar.b(new ai());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.p.f());
        tVar.b(new ah());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.p.e());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.b.f());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.share.d());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.z.m());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.z.l());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.z.j());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.w.e());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.w.g());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.w.f());
        tVar.b(new cs());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.h.g());
        tVar.b(new bl());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.h.c());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.y.b());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.y.c());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.y.f());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.y.d());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.y.e());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.storage.k());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.storage.l());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.ag.b.b.f());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.ag.b.b.g());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.b.e());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.t.c());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.t.b());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.t.d());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.t.a());
        tVar.b(new be());
        tVar.b(new bp());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.storage.g());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.storage.h());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.i.c());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.i.q());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.media.j());
        tVar.b(new JsApiRefreshSession());
        tVar.b(new am());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.pay.o());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.share.o());
        tVar.b(new com.tencent.mm.plugin.appbrand.af.h());
        tVar.b(new am());
        tVar.b(new bv());
        tVar.b(new JsApiMakeVoIPCall());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.z.c());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.z.e());
        tVar.b(new JsApiSetClipboardDataWC());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.bluetooth.a.l());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.bluetooth.a.b());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.bluetooth.a.g());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.bluetooth.a.o());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.bluetooth.a.p());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.bluetooth.a.h());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.bluetooth.a.j());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.bluetooth.a.n());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.bluetooth.a.e());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.bluetooth.a.c());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.bluetooth.a.a());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.bluetooth.a.f());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.bluetooth.a.d());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.bluetooth.a.m());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.bluetooth.a.q());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.bluetooth.a.k());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.bluetooth.a.i());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.bluetooth.b.c());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.bluetooth.b.d());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.bluetooth.b.e());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.bluetooth.b.f());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.bluetooth.b.g());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.bluetooth.b.h());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.bluetooth.b.i());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.miniprogram_navigator.f());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.miniprogram_navigator.e());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.p.q());
        tVar.b(new co());
        tVar.b(new bd());
        tVar.b(new JsApiChooseWeChatContact());
        tVar.b(new JsApiChooseMedia());
        tVar.b(new JsApiUploadEncryptedFileToCDN());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.miniprogram_navigator.d());
        tVar.b(new cb());
        tVar.b(new cu());
        tVar.b(new JsApiGetBackgroundAudioState());
        tVar.b(new JsApiSetBackgroundAudioStateWC());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.audio.j());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.share.p());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.share.b());
        tVar.b(new cc());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.pay.r());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.contact.b());
        tVar.b(new JsApiOpenWeRunSetting());
        tVar.b(new JsApiUploadWeRunData());
        tVar.b(new aq());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.z.h());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.z.q());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.z.s());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.z.t());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.share.s());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.share.r());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.share.u());
        tVar.b(new JsApiShowUpdatableMessageSubscribeButton());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.g.b());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.g.c());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.g.d());
        tVar.b(new JsApiCheckIsSupportFaceDetect());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.bio.face.e());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.bio.face.d());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.bio.face.f());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.bio.face.b());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.bio.face.c());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.ag.e.b.f());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.video.d.c());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.live.d());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.live.c());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.media.n());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.media.o());
        tVar.b(new bn());
        tVar.b(new by());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.share.e());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.share.k());
        tVar.b(new ao());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.share.m());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.share.i());
        tVar.b(new ap());
        tVar.b(new an());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.channels.d());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.channels.e());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.channels.b());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.channels.g());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.channels.f());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.p.d());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.share.g());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.z.p());
        tVar.b(new ax());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.b.i());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.coverview.j());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.miniprogram_navigator.i());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.fakenative.c());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.fakenative.d());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.fakenative.b());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.op_report.b());
        tVar.b(new aa());
        tVar.b(new ao());
        tVar.b(new cr());
        tVar.b(new ad());
        tVar.b(new ct());
        tVar.b(new z());
        tVar.b(new JsApiCheckIsSupportSoterAuthentication());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.bio.soter.c());
        tVar.b(new az());
        tVar.b(new ay());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.o.b.b(com.tencent.mm.plugin.appbrand.jsapi.o.b.a.mgg, bd.btx()));
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.o.b.c(com.tencent.mm.plugin.appbrand.jsapi.o.b.a.mgg, bd.btx()));
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.o.b.d());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.o.a.b(bd.bty()));
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.o.a.c(bd.bty()));
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.o.a.d());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.o.c.b());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.o.c.c());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.o.c.d());
        tVar.b(new cw());
        tVar.b(new at());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.camera.n());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.p.ak());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.audio.k());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.ad.a.d());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.audio.e());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.audio.f());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.audio.m());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.audio.h());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.audio.i());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.audio.g());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.audio.n());
        tVar.b(new JsApiNavigateBackApplication());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.i.k());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.i.i());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.i.f());
        tVar.b(new JsApiCheckBioEnrollment());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.wifi.d());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.wifi.e());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.wifi.c());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.wifi.b());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.wifi.a());
        tVar.b(new JsApiNavigateToDevMiniProgram());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.nfc.g(HCEService.class));
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.nfc.h());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.nfc.f());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.nfc.d());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.nfc.e());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.nfc.rw.i());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.nfc.rw.l());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.nfc.rw.f());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.nfc.rw.e());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.nfc.rw.d());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.nfc.rw.k());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.nfc.rw.m());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.nfc.rw.n());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.nfc.rw.o());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.nfc.rw.g());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.nfc.rw.j());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.nfc.rw.h());
        tVar.b(new ae());
        tVar.b(new ag());
        tVar.b(new af());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.p.g());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.p.aj());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.ui.d());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.ui.b());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.ui.e());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.ui.c());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.z.n());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.z.r());
        tVar.b(new an());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.o.e(com.tencent.mm.plugin.appbrand.jsapi.o.e.mgg, bd.btv()));
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.o.g(bd.btv()));
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.pay.q());
        tVar.b(new w());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.o.d());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.file.am());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.file.an());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.file.r());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.file.s());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.file.t());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.file.ah());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.file.ag());
        tVar.b(new as());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.file.aa());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.file.ae());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.file.al());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.file.k());
        tVar.b(new ap());
        tVar.b(new v());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.file.q());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.file.ab());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.file.af());
        tVar.b(new ar());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.file.z());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.file.ad());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.file.ak());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.file.j());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.file.ao());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.file.u());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.file.p());
        tVar.b(new aq());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.file.n());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.file.o());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.file.ai());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.file.aj());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.file.l());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.file.m());
        tVar.b(new JsApiGetLabInfo());
        tVar.b(new JsApiSetLabInfo());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.ab.a());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.b.b());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.b.c());
        tVar.b(new ca());
        tVar.b(new bw());
        tVar.b(new bx());
        tVar.b(new ce());
        tVar.b(new cf());
        tVar.b(new cg());
        tVar.b(new ch());
        tVar.b(new cj());
        tVar.b(new di());
        tVar.b(new dg());
        tVar.b(new dh());
        tVar.b(new bo());
        tVar.b(new br());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.z.d());
        tVar.b(new JsApiLaunchApplication());
        tVar.b(new JsApiLaunchApplicationDirectly());
        tVar.b(new JsApiAddNativeDownloadTask());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.pay.m());
        tVar.b(new JsApiAddDownloadTask());
        tVar.b(new JsApiAddDownloadTaskStraight());
        tVar.b(new JsApiQueryDownloadTask());
        tVar.b(new JsApiInstallDownloadTask());
        tVar.b(new JsApiPauseDownloadTask());
        tVar.b(new JsApiResumeDownloadTask());
        tVar.b(new JsApiGetInstallState());
        tVar.b(new JsApiCancelDownloadTask());
        tVar.b(new JsApiWriteCommData());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.ui.a());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.p.u());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.p.v());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.j.a());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.j.b());
        ArrayList arrayList = new ArrayList();
        arrayList.add(new com.tencent.mm.plugin.appbrand.jsapi.k.c());
        arrayList.add(new com.tencent.mm.plugin.appbrand.jsapi.k.ai());
        arrayList.add(new com.tencent.mm.plugin.appbrand.jsapi.k.h());
        arrayList.add(new com.tencent.mm.plugin.appbrand.jsapi.k.aa());
        arrayList.add(new com.tencent.mm.plugin.appbrand.jsapi.k.g());
        arrayList.add(new com.tencent.mm.plugin.appbrand.jsapi.k.z());
        arrayList.add(new com.tencent.mm.plugin.appbrand.jsapi.k.d());
        arrayList.add(new com.tencent.mm.plugin.appbrand.jsapi.k.i());
        arrayList.add(new com.tencent.mm.plugin.appbrand.jsapi.k.l());
        arrayList.add(new com.tencent.mm.plugin.appbrand.jsapi.k.v());
        arrayList.add(new com.tencent.mm.plugin.appbrand.jsapi.k.af());
        arrayList.add(new com.tencent.mm.plugin.appbrand.jsapi.k.u());
        arrayList.add(new com.tencent.mm.plugin.appbrand.jsapi.k.p());
        arrayList.add(new com.tencent.mm.plugin.appbrand.jsapi.k.n());
        arrayList.add(new com.tencent.mm.plugin.appbrand.jsapi.k.o());
        arrayList.add(new com.tencent.mm.plugin.appbrand.jsapi.k.q());
        arrayList.add(new com.tencent.mm.plugin.appbrand.jsapi.k.m());
        arrayList.add(new ac());
        arrayList.add(new com.tencent.mm.plugin.appbrand.jsapi.k.j());
        arrayList.add(new com.tencent.mm.plugin.appbrand.jsapi.k.ab());
        arrayList.add(new com.tencent.mm.plugin.appbrand.jsapi.k.e());
        arrayList.add(new y());
        arrayList.add(new com.tencent.mm.plugin.appbrand.jsapi.k.ad());
        arrayList.add(new com.tencent.mm.plugin.appbrand.jsapi.k.s());
        arrayList.add(new com.tencent.mm.plugin.appbrand.jsapi.k.f());
        arrayList.add(new com.tencent.mm.plugin.appbrand.jsapi.k.ah());
        arrayList.add(new com.tencent.mm.plugin.appbrand.jsapi.k.w());
        arrayList.add(new com.tencent.mm.plugin.appbrand.jsapi.k.ae());
        arrayList.add(new com.tencent.mm.plugin.appbrand.jsapi.k.k());
        tVar.bv(arrayList);
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.h5_interact.b());
        tVar.b(new JsApiOpenAdCanvas());
        tVar.b(new ba());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.storage.c());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.profile.c());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.profile.a());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.profile.b());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.l.a());
        tVar.b(new bi());
        tVar.b(new bj());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.offlinevoice.b());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.offlinevoice.c());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.pay.d());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.pay.f());
        tVar.b(new cd());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.pay.k());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.pay.c());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.pay.p());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.pay.g());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.openvoice.a());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.openvoice.f());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.openvoice.c());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.openvoice.b());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.openvoice.e());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.openvoice.d());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.openvoice.h());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.openvoice.j());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.openvoice.g());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.openvoice.k());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.o.h());
        tVar.b(new JsApiGetABTestConfig());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.o.f());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.x.c());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.x.d());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.x.a());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.coverview.i());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.coverview.r());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.coverview.n());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.coverview.g());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.coverview.p());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.coverview.l());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.coverview.h());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.coverview.q());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.coverview.m());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.coverview.e());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.video.d.a());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.video.d.e());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.video.d.d());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.video.d.b());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.ag.e.b.e());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.ag.e.b.i());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.ag.e.b.h());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.ag.e.b.g());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.ag.c.a.a.e());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.ag.c.a.a.i());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.ag.c.a.a.f());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.ag.c.a.a.h());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.ag.c.a.a.g());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.ag.c.b.a.b());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.ag.c.b.a.e());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.ag.c.b.a.c());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.ag.c.b.a.d());
        tVar.b(new cl());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.file.ac());
        tVar.b(new JsApiPrivateAddContact());
        tVar.b(new al());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.coverview.f());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.coverview.o());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.coverview.k());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.media.f());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.p.ap());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.p.ac());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.share.f());
        tVar.b(new JsApiChooseMultiMedia());
        tVar.b(new JsApiRequestSubscribeMessage());
        tVar.b(new bq());
        tVar.b(new JsApiSetBackgroundFetchToken());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.backgroundfetch.a());
        tVar.b(new JsApiTriggerBackgroundFetch());
        tVar.b(new JsApiAddDownloadTaskForNative());
        tVar.b(new JsApiPauseDownloadTaskForNative());
        tVar.b(new JsApiResumeDownloadTaskForNative());
        tVar.b(new JsApiQueryDownloadTaskForNative());
        tVar.b(new JsApiInstallDownloadTaskForNative());
        tVar.b(new JsApiGetInstallStateForNative());
        tVar.b(new JsApiLaunchApplicationForNative());
        tVar.b(new JsApiCancelDownloadTaskForNative());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.appdownload.f());
        tVar.b(new JsApiJumpDownloaderWidgetForNative());
        tVar.b(new cz());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.n.a());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.w.c());
        tVar.b(new cv());
        tVar.bv(com.tencent.mm.plugin.appbrand.jsapi.ui.launcher.d.bIV());
        tVar.b(new ck());
        tVar.b(new av());
        tVar.b(new JsApiGetFinderAccount());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.finder.b());
        tVar.b(new JsApiPostFinderDataItem());
        tVar.b(new JsApiDeleteFinderDataItem());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.finder.c());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.finder.f());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.finder.e());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.finder.g());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.finder.h());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.finder.i());
        tVar.b(new JsApiFetchSendingAndFailProfileFeed());
        tVar.b(new JsApiResendProfileFeed());
        tVar.b(new JsApiFinderEndorsementFinished());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.finder.d());
        tVar.b(new bh());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.d.a());
        tVar.b(new cq());
        tVar.b(new bs());
        tVar.b(new x());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.p.y());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.share.h());
        tVar.b(new cp());
        tVar.b(new JsApiHandleMpChannelAction());
        tVar.b(new JsApiOpenWebViewUseFastLoad());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.camera.l());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.camera.p());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.camera.o());
        tVar.b(new JsApiAddToFavorites());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.share.l());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.share.q());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.share.c());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.share.t());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.fakenative.e());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.fakenative.a());
        tVar.b(new JsApiRemoveSplashScreenshot());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.pay.i());
        tVar.b(new JsApiOnWebPageUrlExposed());
        tVar.b(new JsApiGetRecentUsageList());
        tVar.b(new JsApiOperateRecentUsageList());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.e.b());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.e.c());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.e.d());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.q.b());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.aa.c());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.aa.d());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.aa.f());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.aa.g());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.aa.e());
        tVar.b(new ar());
        tVar.b(new as());
        tVar.b(new bb());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.file.x());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.file.y());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.f.c());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.f.b());
        tVar.b(new bm());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.a.a());
        tVar.b(new com.tencent.mm.plugin.appbrand.jsapi.i.d());
        tVar.b(new bf());
        Map<String, p> map = tVar.lxW;
        AppMethodBeat.o(45423);
        return map;
    }

    public static Map<String, p> bEl() {
        AppMethodBeat.i(45424);
        t tVar = new t();
        tVar.lxV = Util.currentTicks();
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.profile.c());
        tVar.a(new bz());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.z.m());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.z.l());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.z.j());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.h.h());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.h.c());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.h.b());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.h.i());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.h.d());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.h.j());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.h.e());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.h.f());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.p.o());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.p.n());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.p.m());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.w.d());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.w.e());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.w.g());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.w.f());
        tVar.a(new cn());
        tVar.a(new cs());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.r.f());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.r.h());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.p.c());
        tVar.a(new bl());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.video.d.a());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.video.d.e());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.video.d.d());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.video.d.c());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.video.d.b());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.live.b());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.live.h());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.live.f());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.live.d());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.live.a());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.live.g());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.live.e());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.live.c());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.ag.e.b.e());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.ag.e.b.i());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.ag.e.b.f());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.ag.e.b.h());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.ag.c.a.a.e());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.ag.c.a.a.i());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.ag.c.a.a.f());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.ag.c.a.a.h());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.ag.c.b.a.b());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.ag.c.b.a.e());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.ag.c.b.a.c());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.ag.c.b.a.d());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.b.f());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.b.g());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.b.j());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.b.l());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.contact.e());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.contact.f());
        tVar.a(new JsApiPrivateAddContact());
        tVar.a(new cm());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.p.b());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.autofill.e());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.autofill.h());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.autofill.b());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.autofill.g());
        tVar.a(new cu());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.z.t());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.container.a());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.container.c());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.container.b());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.autofill.d());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.autofill.f());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.r.g());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.r.d());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.r.i());
        tVar.a(new ct());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.coverview.i());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.coverview.r());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.coverview.n());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.coverview.g());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.coverview.p());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.coverview.l());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.camera.l());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.camera.p());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.camera.o());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.openvoice.b());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.openvoice.e());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.openvoice.d());
        tVar.a(new com.tencent.mm.plugin.appbrand.debugger.f());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.coverview.e());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.af.g());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.af.i());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.af.h());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.coverview.f());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.coverview.o());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.coverview.k());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.b.h());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.b.m());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.b.k());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.b.a.a.b());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.b.a.a.d());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.b.a.a.c());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.p.t());
        tVar.a(new cl());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.file.ac());
        tVar.a(new al());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.coverview.h());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.coverview.q());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.coverview.m());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.p.ab());
        tVar.a(new z());
        tVar.a(new ai());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.p.f());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.p.v());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.p.u());
        tVar.bw(com.tencent.mm.plugin.appbrand.jsapi.k.aj.bGR());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.ui.d());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.ui.b());
        tVar.a(new ah());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.p.e());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.ui.e());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.ui.c());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.p.d());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.miniprogram_navigator.i());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.miniprogram_navigator.g());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.pay.n());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.pay.l());
        tVar.a(new di());
        tVar.a(new aa());
        tVar.a(new com.tencent.mm.plugin.appbrand.af.h());
        tVar.a(new JsApiOperateWXData());
        tVar.a(new JsApiLogin());
        tVar.a(new JsApiAuthorize());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.z.h());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.z.q());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.z.n());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.z.r());
        tVar.a(new an());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.storage.d());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.storage.j());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.storage.m());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.storage.e());
        tVar.a(new bt());
        tVar.a(new bu());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.ag.d.a.b());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.ag.d.a.d());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.ag.d.a.c());
        tVar.a(new JsApiShowImageOperateSheet());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.ag.a.a.b());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.ag.a.a.d());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.ag.a.a.c());
        tVar.bw(com.tencent.mm.plugin.appbrand.jsapi.ag.b.d.hU(!com.tencent.mm.plugin.appbrand.xweb_ext.c.cdl()));
        tVar.bw(com.tencent.mm.plugin.appbrand.jsapi.ui.launcher.d.bIV());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.v.b());
        tVar.a(new ck());
        tVar.a(new bh());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.d.a());
        tVar.a(new cq());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.file.w());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.p.ap());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.p.ac());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.x.a());
        tVar.a(new JsApiOnWebPageUrlExposed());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.q.b());
        tVar.a(new ar());
        tVar.a(new as());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.p.y());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.a.a());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.share.k());
        tVar.a(new ao());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.share.m());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.share.i());
        tVar.a(new ap());
        tVar.a(new an());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.channels.d());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.channels.e());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.channels.b());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.channels.g());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.channels.f());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.ae.c());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.ae.d());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.ae.b());
        tVar.a(new com.tencent.mm.plugin.appbrand.jsapi.p.p());
        Map<String, p> map = tVar.lxX;
        AppMethodBeat.o(45424);
        return map;
    }

    private void bv(List<p> list) {
        AppMethodBeat.i(45425);
        if (list == null || list.size() <= 0) {
            AppMethodBeat.o(45425);
            return;
        }
        for (p pVar : list) {
            b(pVar);
        }
        AppMethodBeat.o(45425);
    }

    private void b(p pVar) {
        AppMethodBeat.i(45426);
        long currentTicks = Util.currentTicks() - this.lxU;
        if (currentTicks > 1) {
            Log.e("MicroMsg.AppBrandJsApiPool", "addToServicePool api[%s] use[%dms]", pVar.getName(), Long.valueOf(currentTicks));
        }
        if (this.lxW.put(pVar.getName(), pVar) != null) {
            IllegalAccessError illegalAccessError = new IllegalAccessError("Duplicated api instance " + c(pVar));
            AppMethodBeat.o(45426);
            throw illegalAccessError;
        }
        pVar.lxO = lxT;
        this.lxU = Util.currentTicks();
        AppMethodBeat.o(45426);
    }

    private void bw(List<p> list) {
        AppMethodBeat.i(45427);
        if (list == null || list.size() <= 0) {
            AppMethodBeat.o(45427);
            return;
        }
        for (p pVar : list) {
            a(pVar);
        }
        AppMethodBeat.o(45427);
    }

    private void a(p pVar) {
        AppMethodBeat.i(45428);
        long currentTicks = Util.currentTicks() - this.lxV;
        if (currentTicks > 1) {
            Log.e("MicroMsg.AppBrandJsApiPool", "addToPagePool api[%s] use[%dms]", pVar.getName(), Long.valueOf(currentTicks));
        }
        if (this.lxX.put(pVar.getName(), pVar) != null) {
            IllegalAccessError illegalAccessError = new IllegalAccessError("Duplicated api instance " + c(pVar));
            AppMethodBeat.o(45428);
            throw illegalAccessError;
        }
        pVar.lxO = lxT;
        this.lxV = Util.currentTicks();
        AppMethodBeat.o(45428);
    }

    private static String c(p pVar) {
        AppMethodBeat.i(45429);
        String format = String.format(Locale.US, "[%s->%s]", pVar.getName(), pVar.getClass().getSimpleName());
        AppMethodBeat.o(45429);
        return format;
    }
}
