package com.tencent.mm.plugin.vlog.ui;

import com.tencent.matrix.trace.core.AppMethodBeat;
import com.tencent.mm.plugin.recordvideo.plugin.parent.d;
import kotlin.l;

@l(hxD = {1, 1, 16})
public final /* synthetic */ class d {
    public static final /* synthetic */ int[] $EnumSwitchMapping$0;
    public static final /* synthetic */ int[] haE;
    public static final /* synthetic */ int[] uqL;

    static {
        AppMethodBeat.i(191035);
        int[] iArr = new int[d.c.values().length];
        $EnumSwitchMapping$0 = iArr;
        iArr[d.c.BUU.ordinal()] = 1;
        $EnumSwitchMapping$0[d.c.BUV.ordinal()] = 2;
        $EnumSwitchMapping$0[d.c.BUT.ordinal()] = 3;
        $EnumSwitchMapping$0[d.c.BVi.ordinal()] = 4;
        $EnumSwitchMapping$0[d.c.BVx.ordinal()] = 5;
        $EnumSwitchMapping$0[d.c.BVj.ordinal()] = 6;
        $EnumSwitchMapping$0[d.c.BWl.ordinal()] = 7;
        $EnumSwitchMapping$0[d.c.BUZ.ordinal()] = 8;
        $EnumSwitchMapping$0[d.c.BUX.ordinal()] = 9;
        $EnumSwitchMapping$0[d.c.BUY.ordinal()] = 10;
        $EnumSwitchMapping$0[d.c.BWj.ordinal()] = 11;
        $EnumSwitchMapping$0[d.c.BVd.ordinal()] = 12;
        $EnumSwitchMapping$0[d.c.BVn.ordinal()] = 13;
        $EnumSwitchMapping$0[d.c.BVr.ordinal()] = 14;
        $EnumSwitchMapping$0[d.c.BVs.ordinal()] = 15;
        $EnumSwitchMapping$0[d.c.BUW.ordinal()] = 16;
        $EnumSwitchMapping$0[d.c.BWk.ordinal()] = 17;
        $EnumSwitchMapping$0[d.c.BVE.ordinal()] = 18;
        $EnumSwitchMapping$0[d.c.BVt.ordinal()] = 19;
        $EnumSwitchMapping$0[d.c.BVu.ordinal()] = 20;
        $EnumSwitchMapping$0[d.c.BUQ.ordinal()] = 21;
        $EnumSwitchMapping$0[d.c.BVy.ordinal()] = 22;
        $EnumSwitchMapping$0[d.c.BVw.ordinal()] = 23;
        $EnumSwitchMapping$0[d.c.BWV.ordinal()] = 24;
        $EnumSwitchMapping$0[d.c.BVl.ordinal()] = 25;
        $EnumSwitchMapping$0[d.c.BVk.ordinal()] = 26;
        $EnumSwitchMapping$0[d.c.BVg.ordinal()] = 27;
        $EnumSwitchMapping$0[d.c.BVh.ordinal()] = 28;
        $EnumSwitchMapping$0[d.c.BWa.ordinal()] = 29;
        $EnumSwitchMapping$0[d.c.BUG.ordinal()] = 30;
        $EnumSwitchMapping$0[d.c.BVI.ordinal()] = 31;
        $EnumSwitchMapping$0[d.c.BVJ.ordinal()] = 32;
        $EnumSwitchMapping$0[d.c.BVK.ordinal()] = 33;
        $EnumSwitchMapping$0[d.c.BVL.ordinal()] = 34;
        $EnumSwitchMapping$0[d.c.BVM.ordinal()] = 35;
        $EnumSwitchMapping$0[d.c.BWh.ordinal()] = 36;
        $EnumSwitchMapping$0[d.c.BWi.ordinal()] = 37;
        $EnumSwitchMapping$0[d.c.BWv.ordinal()] = 38;
        $EnumSwitchMapping$0[d.c.BWg.ordinal()] = 39;
        $EnumSwitchMapping$0[d.c.BWb.ordinal()] = 40;
        $EnumSwitchMapping$0[d.c.BWc.ordinal()] = 41;
        $EnumSwitchMapping$0[d.c.BWm.ordinal()] = 42;
        $EnumSwitchMapping$0[d.c.BWn.ordinal()] = 43;
        $EnumSwitchMapping$0[d.c.BWd.ordinal()] = 44;
        $EnumSwitchMapping$0[d.c.BWe.ordinal()] = 45;
        $EnumSwitchMapping$0[d.c.BWf.ordinal()] = 46;
        $EnumSwitchMapping$0[d.c.BWq.ordinal()] = 47;
        $EnumSwitchMapping$0[d.c.BWr.ordinal()] = 48;
        $EnumSwitchMapping$0[d.c.BWp.ordinal()] = 49;
        $EnumSwitchMapping$0[d.c.BWu.ordinal()] = 50;
        $EnumSwitchMapping$0[d.c.BWs.ordinal()] = 51;
        $EnumSwitchMapping$0[d.c.BWt.ordinal()] = 52;
        $EnumSwitchMapping$0[d.c.BWw.ordinal()] = 53;
        $EnumSwitchMapping$0[d.c.BWx.ordinal()] = 54;
        $EnumSwitchMapping$0[d.c.BWy.ordinal()] = 55;
        $EnumSwitchMapping$0[d.c.BWz.ordinal()] = 56;
        $EnumSwitchMapping$0[d.c.BWB.ordinal()] = 57;
        $EnumSwitchMapping$0[d.c.BWC.ordinal()] = 58;
        $EnumSwitchMapping$0[d.c.BWA.ordinal()] = 59;
        $EnumSwitchMapping$0[d.c.BWD.ordinal()] = 60;
        $EnumSwitchMapping$0[d.c.BWE.ordinal()] = 61;
        $EnumSwitchMapping$0[d.c.BWF.ordinal()] = 62;
        $EnumSwitchMapping$0[d.c.BWo.ordinal()] = 63;
        $EnumSwitchMapping$0[d.c.BWL.ordinal()] = 64;
        $EnumSwitchMapping$0[d.c.BWK.ordinal()] = 65;
        $EnumSwitchMapping$0[d.c.BWJ.ordinal()] = 66;
        $EnumSwitchMapping$0[d.c.BWM.ordinal()] = 67;
        $EnumSwitchMapping$0[d.c.BVG.ordinal()] = 68;
        $EnumSwitchMapping$0[d.c.BVH.ordinal()] = 69;
        $EnumSwitchMapping$0[d.c.BWG.ordinal()] = 70;
        $EnumSwitchMapping$0[d.c.BWH.ordinal()] = 71;
        $EnumSwitchMapping$0[d.c.BWI.ordinal()] = 72;
        $EnumSwitchMapping$0[d.c.BWN.ordinal()] = 73;
        $EnumSwitchMapping$0[d.c.BWO.ordinal()] = 74;
        $EnumSwitchMapping$0[d.c.BWP.ordinal()] = 75;
        $EnumSwitchMapping$0[d.c.BWQ.ordinal()] = 76;
        $EnumSwitchMapping$0[d.c.BWS.ordinal()] = 77;
        $EnumSwitchMapping$0[d.c.BWR.ordinal()] = 78;
        $EnumSwitchMapping$0[d.c.BWT.ordinal()] = 79;
        $EnumSwitchMapping$0[d.c.BWU.ordinal()] = 80;
        int[] iArr2 = new int[b.values().length];
        haE = iArr2;
        iArr2[b.SINGLE_EDIT.ordinal()] = 1;
        int[] iArr3 = new int[b.values().length];
        uqL = iArr3;
        iArr3[b.SINGLE_EDIT.ordinal()] = 1;
        AppMethodBeat.o(191035);
    }
}
