package com.tencent.mm.plugin.downloader.g;

import com.tencent.matrix.trace.core.AppMethodBeat;
import com.tencent.mm.g.c.cc;
import com.tencent.mm.g.c.ch;
import com.tencent.mm.sdk.storage.IAutoDBItem;
import com.tencent.sqlitelint.behaviour.persistence.IssueStorage;
import com.tencent.thumbplayer.core.downloadproxy.api.TPDownloadProxyEnum;
import com.tencent.tmassistantsdk.downloadservice.DownloadInfo;
import com.tencent.tmassistantsdk.openSDK.QQDownloader.AssistantStore;
import java.lang.reflect.Field;

public final class a extends cc {
    protected static IAutoDBItem.MAutoDBInfo info;

    @Override // com.tencent.mm.sdk.storage.IAutoDBItem
    public final IAutoDBItem.MAutoDBInfo getDBInfo() {
        return info;
    }

    static {
        AppMethodBeat.i(89087);
        IAutoDBItem.MAutoDBInfo mAutoDBInfo = new IAutoDBItem.MAutoDBInfo();
        mAutoDBInfo.fields = new Field[41];
        mAutoDBInfo.columns = new String[42];
        StringBuilder sb = new StringBuilder();
        mAutoDBInfo.columns[0] = "downloadId";
        mAutoDBInfo.colsMap.put("downloadId", "LONG default '-1'  PRIMARY KEY ");
        sb.append(" downloadId LONG default '-1'  PRIMARY KEY ");
        sb.append(", ");
        mAutoDBInfo.primaryKey = "downloadId";
        mAutoDBInfo.columns[1] = "downloadUrl";
        mAutoDBInfo.colsMap.put("downloadUrl", "TEXT default '' ");
        sb.append(" downloadUrl TEXT default '' ");
        sb.append(", ");
        mAutoDBInfo.columns[2] = DownloadInfo.SECONDARYURL;
        mAutoDBInfo.colsMap.put(DownloadInfo.SECONDARYURL, "TEXT default '' ");
        sb.append(" secondaryUrl TEXT default '' ");
        sb.append(", ");
        mAutoDBInfo.columns[3] = "fileSize";
        mAutoDBInfo.colsMap.put("fileSize", "LONG default '0' ");
        sb.append(" fileSize LONG default '0' ");
        sb.append(", ");
        mAutoDBInfo.columns[4] = DownloadInfo.FILENAME;
        mAutoDBInfo.colsMap.put(DownloadInfo.FILENAME, "TEXT default '' ");
        sb.append(" fileName TEXT default '' ");
        sb.append(", ");
        mAutoDBInfo.columns[5] = "filePath";
        mAutoDBInfo.colsMap.put("filePath", "TEXT default '' ");
        sb.append(" filePath TEXT default '' ");
        sb.append(", ");
        mAutoDBInfo.columns[6] = "fileType";
        mAutoDBInfo.colsMap.put("fileType", "INTEGER default '0' ");
        sb.append(" fileType INTEGER default '0' ");
        sb.append(", ");
        mAutoDBInfo.columns[7] = "status";
        mAutoDBInfo.colsMap.put("status", "INTEGER default '0' ");
        sb.append(" status INTEGER default '0' ");
        sb.append(", ");
        mAutoDBInfo.columns[8] = "md5";
        mAutoDBInfo.colsMap.put("md5", "TEXT default '' ");
        sb.append(" md5 TEXT default '' ");
        sb.append(", ");
        mAutoDBInfo.columns[9] = "autoInstall";
        mAutoDBInfo.colsMap.put("autoInstall", "INTEGER default 'false' ");
        sb.append(" autoInstall INTEGER default 'false' ");
        sb.append(", ");
        mAutoDBInfo.columns[10] = "showNotification";
        mAutoDBInfo.colsMap.put("showNotification", "INTEGER default 'false' ");
        sb.append(" showNotification INTEGER default 'false' ");
        sb.append(", ");
        mAutoDBInfo.columns[11] = "sysDownloadId";
        mAutoDBInfo.colsMap.put("sysDownloadId", "LONG default '-1' ");
        sb.append(" sysDownloadId LONG default '-1' ");
        sb.append(", ");
        mAutoDBInfo.columns[12] = "downloaderType";
        mAutoDBInfo.colsMap.put("downloaderType", "INTEGER default '0' ");
        sb.append(" downloaderType INTEGER default '0' ");
        sb.append(", ");
        mAutoDBInfo.columns[13] = "appId";
        mAutoDBInfo.colsMap.put("appId", "TEXT default '' ");
        sb.append(" appId TEXT default '' ");
        sb.append(", ");
        mAutoDBInfo.columns[14] = "downloadUrlHashCode";
        mAutoDBInfo.colsMap.put("downloadUrlHashCode", "INTEGER default '0' ");
        sb.append(" downloadUrlHashCode INTEGER default '0' ");
        sb.append(", ");
        mAutoDBInfo.columns[15] = AssistantStore.DownloadInfos.DownloadInfoColumns.PACKAGENAME;
        mAutoDBInfo.colsMap.put(AssistantStore.DownloadInfos.DownloadInfoColumns.PACKAGENAME, "TEXT default '' ");
        sb.append(" packageName TEXT default '' ");
        sb.append(", ");
        mAutoDBInfo.columns[16] = "downloadedSize";
        mAutoDBInfo.colsMap.put("downloadedSize", "LONG default '0' ");
        sb.append(" downloadedSize LONG default '0' ");
        sb.append(", ");
        mAutoDBInfo.columns[17] = "totalSize";
        mAutoDBInfo.colsMap.put("totalSize", "LONG default '0' ");
        sb.append(" totalSize LONG default '0' ");
        sb.append(", ");
        mAutoDBInfo.columns[18] = "autoDownload";
        mAutoDBInfo.colsMap.put("autoDownload", "INTEGER default 'false' ");
        sb.append(" autoDownload INTEGER default 'false' ");
        sb.append(", ");
        mAutoDBInfo.columns[19] = "channelId";
        mAutoDBInfo.colsMap.put("channelId", "TEXT default '' ");
        sb.append(" channelId TEXT default '' ");
        sb.append(", ");
        mAutoDBInfo.columns[20] = "scene";
        mAutoDBInfo.colsMap.put("scene", "INTEGER default '0' ");
        sb.append(" scene INTEGER default '0' ");
        sb.append(", ");
        mAutoDBInfo.columns[21] = "errCode";
        mAutoDBInfo.colsMap.put("errCode", "INTEGER default '0' ");
        sb.append(" errCode INTEGER default '0' ");
        sb.append(", ");
        mAutoDBInfo.columns[22] = "startTime";
        mAutoDBInfo.colsMap.put("startTime", "LONG default '0' ");
        sb.append(" startTime LONG default '0' ");
        sb.append(", ");
        mAutoDBInfo.columns[23] = "startSize";
        mAutoDBInfo.colsMap.put("startSize", "LONG default '0' ");
        sb.append(" startSize LONG default '0' ");
        sb.append(", ");
        mAutoDBInfo.columns[24] = "startState";
        mAutoDBInfo.colsMap.put("startState", "INTEGER default '0' ");
        sb.append(" startState INTEGER default '0' ");
        sb.append(", ");
        mAutoDBInfo.columns[25] = "fromWeApp";
        mAutoDBInfo.colsMap.put("fromWeApp", "INTEGER default 'false' ");
        sb.append(" fromWeApp INTEGER default 'false' ");
        sb.append(", ");
        mAutoDBInfo.columns[26] = "downloadInWifi";
        mAutoDBInfo.colsMap.put("downloadInWifi", "INTEGER default 'false' ");
        sb.append(" downloadInWifi INTEGER default 'false' ");
        sb.append(", ");
        mAutoDBInfo.columns[27] = IssueStorage.COLUMN_EXT_INFO;
        mAutoDBInfo.colsMap.put(IssueStorage.COLUMN_EXT_INFO, "TEXT default '' ");
        sb.append(" extInfo TEXT default '' ");
        sb.append(", ");
        mAutoDBInfo.columns[28] = "finishTime";
        mAutoDBInfo.colsMap.put("finishTime", "LONG default '0' ");
        sb.append(" finishTime LONG default '0' ");
        sb.append(", ");
        mAutoDBInfo.columns[29] = "isSecondDownload";
        mAutoDBInfo.colsMap.put("isSecondDownload", "INTEGER default 'false' ");
        sb.append(" isSecondDownload INTEGER default 'false' ");
        sb.append(", ");
        mAutoDBInfo.columns[30] = "fromDownloadApp";
        mAutoDBInfo.colsMap.put("fromDownloadApp", "INTEGER default 'false' ");
        sb.append(" fromDownloadApp INTEGER default 'false' ");
        sb.append(", ");
        mAutoDBInfo.columns[31] = ch.COL_UPDATETIME;
        mAutoDBInfo.colsMap.put(ch.COL_UPDATETIME, "LONG default '0' ");
        sb.append(" updateTime LONG default '0' ");
        sb.append(", ");
        mAutoDBInfo.columns[32] = "reserveInWifi";
        mAutoDBInfo.colsMap.put("reserveInWifi", "INTEGER default 'false' ");
        sb.append(" reserveInWifi INTEGER default 'false' ");
        sb.append(", ");
        mAutoDBInfo.columns[33] = TPDownloadProxyEnum.USER_SSID;
        mAutoDBInfo.colsMap.put(TPDownloadProxyEnum.USER_SSID, "INTEGER default '0' ");
        sb.append(" ssid INTEGER default '0' ");
        sb.append(", ");
        mAutoDBInfo.columns[34] = "uiarea";
        mAutoDBInfo.colsMap.put("uiarea", "INTEGER default '0' ");
        sb.append(" uiarea INTEGER default '0' ");
        sb.append(", ");
        mAutoDBInfo.columns[35] = "noticeId";
        mAutoDBInfo.colsMap.put("noticeId", "INTEGER default '0' ");
        sb.append(" noticeId INTEGER default '0' ");
        sb.append(", ");
        mAutoDBInfo.columns[36] = "downloadType";
        mAutoDBInfo.colsMap.put("downloadType", "INTEGER default '0' ");
        sb.append(" downloadType INTEGER default '0' ");
        sb.append(", ");
        mAutoDBInfo.columns[37] = "startScene";
        mAutoDBInfo.colsMap.put("startScene", "INTEGER default '0' ");
        sb.append(" startScene INTEGER default '0' ");
        sb.append(", ");
        mAutoDBInfo.columns[38] = "sectionMd5Byte";
        mAutoDBInfo.colsMap.put("sectionMd5Byte", "BLOB");
        sb.append(" sectionMd5Byte BLOB");
        sb.append(", ");
        mAutoDBInfo.columns[39] = "rawAppId";
        mAutoDBInfo.colsMap.put("rawAppId", "TEXT default '' ");
        sb.append(" rawAppId TEXT default '' ");
        sb.append(", ");
        mAutoDBInfo.columns[40] = "notificationTitle";
        mAutoDBInfo.colsMap.put("notificationTitle", "TEXT default '' ");
        sb.append(" notificationTitle TEXT default '' ");
        mAutoDBInfo.columns[41] = "rowid";
        mAutoDBInfo.sql = sb.toString();
        info = mAutoDBInfo;
        AppMethodBeat.o(89087);
    }
}
