package com.tencent.mm.g.b.a;

import com.tencent.matrix.trace.core.AppMethodBeat;
import com.tencent.midas.comm.log.util.APLogFileUtil;
import com.tencent.mm.plugin.report.a;
import com.tencent.mm.sdk.platformtools.Util;
import java.util.Arrays;

public final class y extends a {
    private int elE = 0;
    private long elF = 0;
    private long elG = 0;
    private long elH = 0;
    private long elI = 0;
    private long elJ = 0;
    private long elK = 0;
    private long elL = 0;
    private long elM = 0;
    private String elN = "";
    private long elO = 0;
    private String elP = "";
    private long elQ = 0;
    private long elR = 0;
    private long elS = 0;
    private long elT = 0;
    private long elU = 0;
    private long elV = 0;
    private long elW = 0;
    private long elX = 0;
    private long elY = 0;
    private long elZ = 0;
    private String emA = "";
    private long emB = 0;
    private String emC = "";
    private long emD = 0;
    private String emE = "";
    private long emF = 0;
    private String emG = "";
    private long emH = 0;
    private long emI = 0;
    private long emJ = 0;
    private long emK = 0;
    private long ema = 0;
    private long emb = 0;
    private long emc = 0;
    private String emd = "";
    private long eme = 0;
    private long emf = 0;
    private long emg = 0;
    private long emh = 0;
    private long emi = 0;
    private long emj = 0;
    private long emk = 0;
    private long eml = 0;
    private long emm = 0;
    private long emn = 0;
    private long emo = 0;
    private long emp = 0;
    private long emq = 0;
    private long emr = 0;
    private long ems = 0;
    private long emt = 0;
    private long emu = 0;
    private long emv = 0;
    private long emw = 0;
    private long emx = 0;
    private long emy = 0;
    private int emz = 0;

    public y() {
    }

    public y(String str) {
        String[] split;
        String[] strArr;
        AppMethodBeat.i(149900);
        if (!(str == null || (split = str.split(",")) == null)) {
            if (split.length < 59) {
                strArr = new String[59];
                Arrays.fill(strArr, 0, 59, "");
                System.arraycopy(split, 0, strArr, 0, split.length);
            } else {
                strArr = split;
            }
            this.elE = Util.getInt(strArr[0], 0);
            this.elF = Util.getLong(strArr[1], 0);
            this.elG = Util.getLong(strArr[2], 0);
            this.elH = Util.getLong(strArr[3], 0);
            this.elI = Util.getLong(strArr[4], 0);
            this.elJ = Util.getLong(strArr[5], 0);
            this.elK = Util.getLong(strArr[6], 0);
            this.elL = Util.getLong(strArr[7], 0);
            this.elM = Util.getLong(strArr[8], 0);
            this.elN = x("SvrIP", strArr[9], true);
            this.elO = Util.getLong(strArr[10], 0);
            this.elP = x("FileKey", strArr[11], true);
            this.elQ = Util.getLong(strArr[12], 0);
            this.elR = Util.getLong(strArr[13], 0);
            this.elS = Util.getLong(strArr[14], 0);
            this.elT = Util.getLong(strArr[15], 0);
            this.elU = Util.getLong(strArr[16], 0);
            this.elV = Util.getLong(strArr[17], 0);
            this.elW = Util.getLong(strArr[18], 0);
            this.elX = Util.getLong(strArr[19], 0);
            this.elY = Util.getLong(strArr[20], 0);
            this.elZ = Util.getLong(strArr[21], 0);
            this.ema = Util.getLong(strArr[22], 0);
            this.emb = Util.getLong(strArr[23], 0);
            this.emc = Util.getLong(strArr[24], 0);
            this.emd = x("UUID", strArr[25], true);
            this.eme = Util.getLong(strArr[26], 0);
            this.emf = Util.getLong(strArr[27], 0);
            this.emg = Util.getLong(strArr[28], 0);
            this.emh = Util.getLong(strArr[29], 0);
            this.emi = Util.getLong(strArr[30], 0);
            this.emj = Util.getLong(strArr[31], 0);
            this.emk = Util.getLong(strArr[32], 0);
            this.eml = Util.getLong(strArr[33], 0);
            this.emm = Util.getLong(strArr[34], 0);
            this.emn = Util.getLong(strArr[35], 0);
            this.emo = Util.getLong(strArr[36], 0);
            this.emp = Util.getLong(strArr[37], 0);
            this.emq = Util.getLong(strArr[38], 0);
            this.emr = Util.getLong(strArr[39], 0);
            this.ems = Util.getLong(strArr[40], 0);
            this.emt = Util.getLong(strArr[41], 0);
            this.emu = Util.getLong(strArr[42], 0);
            this.emv = Util.getLong(strArr[43], 0);
            this.emw = Util.getLong(strArr[44], 0);
            this.emx = Util.getLong(strArr[45], 0);
            this.emy = Util.getLong(strArr[46], 0);
            this.emz = Util.getInt(strArr[47], 0);
            this.emA = x("UsedIp1", strArr[48], true);
            this.emB = Util.getLong(strArr[49], 0);
            this.emC = x("UsedIp2", strArr[50], true);
            this.emD = Util.getLong(strArr[51], 0);
            this.emE = x("UsedIp3", strArr[52], true);
            this.emF = Util.getLong(strArr[53], 0);
            this.emG = x("UsedIp4", strArr[54], true);
            this.emH = Util.getLong(strArr[55], 0);
            this.emI = Util.getLong(strArr[56], 0);
            this.emJ = Util.getLong(strArr[57], 0);
            this.emK = Util.getLong(strArr[58], 0);
        }
        AppMethodBeat.o(149900);
    }

    @Override // com.tencent.mm.plugin.report.a
    public final int getId() {
        return 10421;
    }

    @Override // com.tencent.mm.plugin.report.a
    public final String abV() {
        AppMethodBeat.i(149901);
        StringBuffer stringBuffer = new StringBuffer();
        stringBuffer.append(this.elE);
        stringBuffer.append(",");
        stringBuffer.append(this.elF);
        stringBuffer.append(",");
        stringBuffer.append(this.elG);
        stringBuffer.append(",");
        stringBuffer.append(this.elH);
        stringBuffer.append(",");
        stringBuffer.append(this.elI);
        stringBuffer.append(",");
        stringBuffer.append(this.elJ);
        stringBuffer.append(",");
        stringBuffer.append(this.elK);
        stringBuffer.append(",");
        stringBuffer.append(this.elL);
        stringBuffer.append(",");
        stringBuffer.append(this.elM);
        stringBuffer.append(",");
        stringBuffer.append(this.elN);
        stringBuffer.append(",");
        stringBuffer.append(this.elO);
        stringBuffer.append(",");
        stringBuffer.append(this.elP);
        stringBuffer.append(",");
        stringBuffer.append(this.elQ);
        stringBuffer.append(",");
        stringBuffer.append(this.elR);
        stringBuffer.append(",");
        stringBuffer.append(this.elS);
        stringBuffer.append(",");
        stringBuffer.append(this.elT);
        stringBuffer.append(",");
        stringBuffer.append(this.elU);
        stringBuffer.append(",");
        stringBuffer.append(this.elV);
        stringBuffer.append(",");
        stringBuffer.append(this.elW);
        stringBuffer.append(",");
        stringBuffer.append(this.elX);
        stringBuffer.append(",");
        stringBuffer.append(this.elY);
        stringBuffer.append(",");
        stringBuffer.append(this.elZ);
        stringBuffer.append(",");
        stringBuffer.append(this.ema);
        stringBuffer.append(",");
        stringBuffer.append(this.emb);
        stringBuffer.append(",");
        stringBuffer.append(this.emc);
        stringBuffer.append(",");
        stringBuffer.append(this.emd);
        stringBuffer.append(",");
        stringBuffer.append(this.eme);
        stringBuffer.append(",");
        stringBuffer.append(this.emf);
        stringBuffer.append(",");
        stringBuffer.append(this.emg);
        stringBuffer.append(",");
        stringBuffer.append(this.emh);
        stringBuffer.append(",");
        stringBuffer.append(this.emi);
        stringBuffer.append(",");
        stringBuffer.append(this.emj);
        stringBuffer.append(",");
        stringBuffer.append(this.emk);
        stringBuffer.append(",");
        stringBuffer.append(this.eml);
        stringBuffer.append(",");
        stringBuffer.append(this.emm);
        stringBuffer.append(",");
        stringBuffer.append(this.emn);
        stringBuffer.append(",");
        stringBuffer.append(this.emo);
        stringBuffer.append(",");
        stringBuffer.append(this.emp);
        stringBuffer.append(",");
        stringBuffer.append(this.emq);
        stringBuffer.append(",");
        stringBuffer.append(this.emr);
        stringBuffer.append(",");
        stringBuffer.append(this.ems);
        stringBuffer.append(",");
        stringBuffer.append(this.emt);
        stringBuffer.append(",");
        stringBuffer.append(this.emu);
        stringBuffer.append(",");
        stringBuffer.append(this.emv);
        stringBuffer.append(",");
        stringBuffer.append(this.emw);
        stringBuffer.append(",");
        stringBuffer.append(this.emx);
        stringBuffer.append(",");
        stringBuffer.append(this.emy);
        stringBuffer.append(",");
        stringBuffer.append(this.emz);
        stringBuffer.append(",");
        stringBuffer.append(this.emA);
        stringBuffer.append(",");
        stringBuffer.append(this.emB);
        stringBuffer.append(",");
        stringBuffer.append(this.emC);
        stringBuffer.append(",");
        stringBuffer.append(this.emD);
        stringBuffer.append(",");
        stringBuffer.append(this.emE);
        stringBuffer.append(",");
        stringBuffer.append(this.emF);
        stringBuffer.append(",");
        stringBuffer.append(this.emG);
        stringBuffer.append(",");
        stringBuffer.append(this.emH);
        stringBuffer.append(",");
        stringBuffer.append(this.emI);
        stringBuffer.append(",");
        stringBuffer.append(this.emJ);
        stringBuffer.append(",");
        stringBuffer.append(this.emK);
        String stringBuffer2 = stringBuffer.toString();
        aMq(stringBuffer2);
        AppMethodBeat.o(149901);
        return stringBuffer2;
    }

    @Override // com.tencent.mm.plugin.report.a
    public final String abW() {
        AppMethodBeat.i(149902);
        StringBuffer stringBuffer = new StringBuffer();
        stringBuffer.append("CientErrNo:").append(this.elE);
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("OpType:").append(this.elF);
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("OpStartTs:").append(this.elG);
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("OpEndTs:").append(this.elH);
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("NetType:").append(this.elI);
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("FileType:").append(this.elJ);
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("FileSize:").append(this.elK);
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("CDNErrNo:").append(this.elL);
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("CDNOpType:").append(this.elM);
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("SvrIP:").append(this.elN);
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("IPCount:").append(this.elO);
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("FileKey:").append(this.elP);
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("SliceCount:").append(this.elQ);
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("TransportSize:").append(this.elR);
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("ConnTotalCost:").append(this.elS);
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("ConnTryTimes:").append(this.elT);
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("CDNTransfStartTs:").append(this.elU);
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("CDNTransfEndTs:").append(this.elV);
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("IsHitCache:").append(this.elW);
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("CompressPicLevel:").append(this.elX);
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("SrcFileSize:").append(this.elY);
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("ImgSource:").append(this.elZ);
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("ResolutionX:").append(this.ema);
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("ResolutionY:").append(this.emb);
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("ReportCode:").append(this.emc);
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("UUID:").append(this.emd);
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("ETLTime:").append(this.eme);
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("PTLTime:").append(this.emf);
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("ETLSize:").append(this.emg);
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("PTLSize:").append(this.emh);
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("SkeyFailCount:").append(this.emi);
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("SKeyTimeoutCount:").append(this.emj);
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("ConnectCount:").append(this.emk);
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("ConnectTotalMS:").append(this.eml);
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("ConnectAvgMS:").append(this.emm);
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("ConnectVarianceMS:").append(this.emn);
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("ConnectMinMS:").append(this.emo);
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("ConnectMaxMS:").append(this.emp);
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("TransforCount:").append(this.emq);
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("TransforTotalMS:").append(this.emr);
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("TransforAvgMS:").append(this.ems);
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("TransforVarianceMS:").append(this.emt);
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("TransforMinMS:").append(this.emu);
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("TransforMaxMS:").append(this.emv);
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("IsProgressiveJPEG:").append(this.emw);
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("WaitSec:").append(this.emx);
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("LastPort:").append(this.emy);
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("ConnErrorCode:").append(this.emz);
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("UsedIp1:").append(this.emA);
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("UsedPort1:").append(this.emB);
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("UsedIp2:").append(this.emC);
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("UsedPort2:").append(this.emD);
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("UsedIp3:").append(this.emE);
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("UsedPort3:").append(this.emF);
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("UsedIp4:").append(this.emG);
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("UsedPort4:").append(this.emH);
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("LogCreateTime:").append(this.emI);
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("LogReportTime:").append(this.emJ);
        stringBuffer.append(APLogFileUtil.SEPARATOR_LINE);
        stringBuffer.append("LogReportSvrTime:").append(this.emK);
        String stringBuffer2 = stringBuffer.toString();
        AppMethodBeat.o(149902);
        return stringBuffer2;
    }
}
