package com.tencent.mm.boot.svg.code.drawable;

import android.graphics.Canvas;
import android.graphics.Matrix;
import android.graphics.Paint;
import android.graphics.Path;
import android.os.Looper;
import com.tencent.mm.svg.WeChatSVGRenderC2Java;
import com.tencent.mm.svg.c;
import com.tencent.smtt.sdk.WebView;

public class amp1 extends c {
    private final int height = 51;
    private final int width = 34;

    /* JADX INFO: Can't fix incorrect switch cases order, some code will duplicate */
    @Override // com.tencent.mm.svg.c
    public int doCommand(int i2, Object... objArr) {
        switch (i2) {
            case 0:
                return 34;
            case 1:
                return 51;
            case 2:
                Canvas canvas = (Canvas) objArr[0];
                Looper looper = (Looper) objArr[1];
                Matrix instanceMatrix = c.instanceMatrix(looper);
                float[] instanceMatrixArray = c.instanceMatrixArray(looper);
                Paint instancePaint = c.instancePaint(looper);
                instancePaint.setFlags(385);
                instancePaint.setStyle(Paint.Style.FILL);
                Paint instancePaint2 = c.instancePaint(looper);
                instancePaint2.setFlags(385);
                instancePaint2.setStyle(Paint.Style.STROKE);
                instancePaint.setColor(WebView.NIGHT_MODE_COLOR);
                instancePaint2.setStrokeWidth(1.0f);
                instancePaint2.setStrokeCap(Paint.Cap.BUTT);
                instancePaint2.setStrokeJoin(Paint.Join.MITER);
                instancePaint2.setStrokeMiter(4.0f);
                instancePaint2.setPathEffect(null);
                c.instancePaint(instancePaint2, looper).setStrokeWidth(1.0f);
                canvas.save();
                Paint instancePaint3 = c.instancePaint(instancePaint, looper);
                instancePaint3.setColor(-1);
                float[] matrixFloatArray = c.setMatrixFloatArray(instanceMatrixArray, 1.0f, 0.0f, -50.0f, 0.0f, 1.0f, -50.0f, 0.0f, 0.0f, 1.0f);
                instanceMatrix.reset();
                instanceMatrix.setValues(matrixFloatArray);
                canvas.concat(instanceMatrix);
                canvas.save();
                float[] matrixFloatArray2 = c.setMatrixFloatArray(matrixFloatArray, 1.0f, 0.0f, 50.666668f, 0.0f, 1.0f, 50.25f, 0.0f, 0.0f, 1.0f);
                instanceMatrix.reset();
                instanceMatrix.setValues(matrixFloatArray2);
                canvas.concat(instanceMatrix);
                canvas.save();
                Paint instancePaint4 = c.instancePaint(instancePaint3, looper);
                Path instancePath = c.instancePath(looper);
                instancePath.moveTo(0.0f, 46.666668f);
                instancePath.lineTo(10.0f, 46.666668f);
                instancePath.lineTo(10.0f, 50.0f);
                instancePath.lineTo(0.0f, 50.0f);
                instancePath.lineTo(0.0f, 46.666668f);
                instancePath.close();
                canvas.drawPath(instancePath, instancePaint4);
                canvas.restore();
                Paint instancePaint5 = c.instancePaint(instancePaint3, looper);
                instancePaint5.setColor(-1);
                Path instancePath2 = c.instancePath(looper);
                instancePath2.moveTo(0.0f, 40.0f);
                instancePath2.lineTo(13.333333f, 40.0f);
                instancePath2.lineTo(13.333333f, 43.333332f);
                instancePath2.lineTo(0.0f, 43.333332f);
                instancePath2.lineTo(0.0f, 40.0f);
                instancePath2.close();
                canvas.saveLayerAlpha(null, 76, 31);
                canvas.drawPath(instancePath2, c.instancePaint(instancePaint5, looper));
                canvas.restore();
                Paint instancePaint6 = c.instancePaint(instancePaint3, looper);
                instancePaint6.setColor(-1);
                Path instancePath3 = c.instancePath(looper);
                instancePath3.moveTo(0.0f, 33.333332f);
                instancePath3.lineTo(16.666666f, 33.333332f);
                instancePath3.lineTo(16.666666f, 36.666664f);
                instancePath3.lineTo(0.0f, 36.666664f);
                instancePath3.lineTo(0.0f, 33.333332f);
                instancePath3.close();
                canvas.saveLayerAlpha(null, 76, 31);
                canvas.drawPath(instancePath3, c.instancePaint(instancePaint6, looper));
                canvas.restore();
                Paint instancePaint7 = c.instancePaint(instancePaint3, looper);
                instancePaint7.setColor(-1);
                Path instancePath4 = c.instancePath(looper);
                instancePath4.moveTo(0.0f, 26.666666f);
                instancePath4.lineTo(20.0f, 26.666666f);
                instancePath4.lineTo(20.0f, 30.0f);
                instancePath4.lineTo(0.0f, 30.0f);
                instancePath4.lineTo(0.0f, 26.666666f);
                instancePath4.close();
                canvas.saveLayerAlpha(null, 76, 31);
                canvas.drawPath(instancePath4, c.instancePaint(instancePaint7, looper));
                canvas.restore();
                Paint instancePaint8 = c.instancePaint(instancePaint3, looper);
                instancePaint8.setColor(-1);
                Path instancePath5 = c.instancePath(looper);
                instancePath5.moveTo(0.0f, 20.0f);
                instancePath5.lineTo(23.333334f, 20.0f);
                instancePath5.lineTo(23.333334f, 23.333334f);
                instancePath5.lineTo(0.0f, 23.333334f);
                instancePath5.lineTo(0.0f, 20.0f);
                instancePath5.close();
                canvas.saveLayerAlpha(null, 76, 31);
                canvas.drawPath(instancePath5, c.instancePaint(instancePaint8, looper));
                canvas.restore();
                Paint instancePaint9 = c.instancePaint(instancePaint3, looper);
                instancePaint9.setColor(-1);
                Path instancePath6 = c.instancePath(looper);
                instancePath6.moveTo(0.0f, 13.333333f);
                instancePath6.lineTo(26.666666f, 13.333333f);
                instancePath6.lineTo(26.666666f, 16.666666f);
                instancePath6.lineTo(0.0f, 16.666666f);
                instancePath6.lineTo(0.0f, 13.333333f);
                instancePath6.close();
                canvas.saveLayerAlpha(null, 76, 31);
                canvas.drawPath(instancePath6, c.instancePaint(instancePaint9, looper));
                canvas.restore();
                Paint instancePaint10 = c.instancePaint(instancePaint3, looper);
                instancePaint10.setColor(-1);
                Path instancePath7 = c.instancePath(looper);
                instancePath7.moveTo(0.0f, 6.6666665f);
                instancePath7.lineTo(30.0f, 6.6666665f);
                instancePath7.lineTo(30.0f, 10.0f);
                instancePath7.lineTo(0.0f, 10.0f);
                instancePath7.close();
                WeChatSVGRenderC2Java.setFillType(instancePath7, 1);
                canvas.saveLayerAlpha(null, 76, 31);
                Paint instancePaint11 = c.instancePaint(instancePaint10, looper);
                WeChatSVGRenderC2Java.setFillType(instancePath7, 2);
                canvas.drawPath(instancePath7, instancePaint11);
                canvas.restore();
                Paint instancePaint12 = c.instancePaint(instancePaint3, looper);
                instancePaint12.setColor(-1);
                Path instancePath8 = c.instancePath(looper);
                instancePath8.moveTo(0.0f, 0.0f);
                instancePath8.lineTo(33.333332f, 0.0f);
                instancePath8.lineTo(33.333332f, 3.3333333f);
                instancePath8.lineTo(0.0f, 3.3333333f);
                instancePath8.lineTo(0.0f, 0.0f);
                instancePath8.close();
                canvas.saveLayerAlpha(null, 76, 31);
                canvas.drawPath(instancePath8, c.instancePaint(instancePaint12, looper));
                canvas.restore();
                canvas.restore();
                canvas.restore();
                c.done(looper);
                break;
        }
        return 0;
    }
}
