package com.tencent.mm.boot.svg.code.drawable;

import android.graphics.Canvas;
import android.graphics.Matrix;
import android.graphics.Paint;
import android.graphics.Path;
import android.os.Looper;
import com.tencent.mm.svg.WeChatSVGRenderC2Java;
import com.tencent.mm.svg.c;
import com.tencent.smtt.sdk.WebView;

public class sight_icon_keyboard extends c {
    private final int height = 90;
    private final int width = 90;

    /* JADX INFO: Can't fix incorrect switch cases order, some code will duplicate */
    @Override // com.tencent.mm.svg.c
    public int doCommand(int i2, Object... objArr) {
        switch (i2) {
            case 0:
                return 90;
            case 1:
                return 90;
            case 2:
                Canvas canvas = (Canvas) objArr[0];
                Looper looper = (Looper) objArr[1];
                Matrix instanceMatrix = c.instanceMatrix(looper);
                float[] instanceMatrixArray = c.instanceMatrixArray(looper);
                Paint instancePaint = c.instancePaint(looper);
                instancePaint.setFlags(385);
                instancePaint.setStyle(Paint.Style.FILL);
                Paint instancePaint2 = c.instancePaint(looper);
                instancePaint2.setFlags(385);
                instancePaint2.setStyle(Paint.Style.STROKE);
                instancePaint.setColor(WebView.NIGHT_MODE_COLOR);
                instancePaint2.setStrokeWidth(1.0f);
                instancePaint2.setStrokeCap(Paint.Cap.BUTT);
                instancePaint2.setStrokeJoin(Paint.Join.MITER);
                instancePaint2.setStrokeMiter(4.0f);
                instancePaint2.setPathEffect(null);
                c.instancePaint(instancePaint2, looper).setStrokeWidth(1.0f);
                canvas.save();
                Paint instancePaint3 = c.instancePaint(instancePaint, looper);
                instancePaint3.setColor(-1);
                float[] matrixFloatArray = c.setMatrixFloatArray(instanceMatrixArray, 1.0f, 0.0f, 16.0f, 0.0f, 1.0f, 30.0f, 0.0f, 0.0f, 1.0f);
                instanceMatrix.reset();
                instanceMatrix.setValues(matrixFloatArray);
                canvas.concat(instanceMatrix);
                canvas.save();
                Paint instancePaint4 = c.instancePaint(instancePaint3, looper);
                Path instancePath = c.instancePath(looper);
                instancePath.moveTo(1.7763568E-15f, 0.0f);
                instancePath.lineTo(6.0f, 0.0f);
                instancePath.cubicTo(5.9900165f, 2.0f, 5.9900165f, 4.0f, 6.0f, 6.0f);
                instancePath.lineTo(1.7763568E-15f, 6.0f);
                instancePath.lineTo(1.7763568E-15f, 0.0f);
                instancePath.lineTo(1.7763568E-15f, 0.0f);
                instancePath.close();
                WeChatSVGRenderC2Java.setFillType(instancePath, 2);
                canvas.drawPath(instancePath, instancePaint4);
                canvas.restore();
                canvas.save();
                Paint instancePaint5 = c.instancePaint(instancePaint3, looper);
                Path instancePath2 = c.instancePath(looper);
                instancePath2.moveTo(10.0f, 0.0f);
                instancePath2.lineTo(16.0f, 0.0f);
                instancePath2.lineTo(16.0f, 6.0f);
                instancePath2.lineTo(10.0f, 6.0f);
                instancePath2.cubicTo(10.009983f, 4.0f, 10.009983f, 2.0f, 10.0f, 0.0f);
                instancePath2.lineTo(10.0f, 0.0f);
                instancePath2.close();
                WeChatSVGRenderC2Java.setFillType(instancePath2, 2);
                canvas.drawPath(instancePath2, instancePaint5);
                canvas.restore();
                canvas.save();
                Paint instancePaint6 = c.instancePaint(instancePaint3, looper);
                Path instancePath3 = c.instancePath(looper);
                instancePath3.moveTo(21.0f, 0.0f);
                instancePath3.lineTo(27.0f, 0.0f);
                instancePath3.lineTo(27.0f, 6.0f);
                instancePath3.lineTo(21.0f, 6.0f);
                instancePath3.lineTo(21.0f, 0.0f);
                instancePath3.lineTo(21.0f, 0.0f);
                instancePath3.close();
                WeChatSVGRenderC2Java.setFillType(instancePath3, 2);
                canvas.drawPath(instancePath3, instancePaint6);
                canvas.restore();
                canvas.save();
                Paint instancePaint7 = c.instancePaint(instancePaint3, looper);
                Path instancePath4 = c.instancePath(looper);
                instancePath4.moveTo(31.0f, 0.0f);
                instancePath4.lineTo(37.0f, 0.0f);
                instancePath4.lineTo(37.0f, 6.0f);
                instancePath4.lineTo(31.0f, 6.0f);
                instancePath4.cubicTo(31.009983f, 4.0f, 31.009983f, 2.0f, 31.0f, 0.0f);
                instancePath4.lineTo(31.0f, 0.0f);
                instancePath4.close();
                WeChatSVGRenderC2Java.setFillType(instancePath4, 2);
                canvas.drawPath(instancePath4, instancePaint7);
                canvas.restore();
                canvas.save();
                Paint instancePaint8 = c.instancePaint(instancePaint3, looper);
                Path instancePath5 = c.instancePath(looper);
                instancePath5.moveTo(42.0f, 0.0f);
                instancePath5.lineTo(48.0f, 0.0f);
                instancePath5.cubicTo(47.990017f, 2.0f, 47.990017f, 4.0f, 48.0f, 6.0f);
                instancePath5.lineTo(42.0f, 6.0f);
                instancePath5.lineTo(42.0f, 0.0f);
                instancePath5.lineTo(42.0f, 0.0f);
                instancePath5.close();
                WeChatSVGRenderC2Java.setFillType(instancePath5, 2);
                canvas.drawPath(instancePath5, instancePaint8);
                canvas.restore();
                canvas.save();
                Paint instancePaint9 = c.instancePaint(instancePaint3, looper);
                Path instancePath6 = c.instancePath(looper);
                instancePath6.moveTo(52.0f, 0.0f);
                instancePath6.lineTo(58.0f, 0.0f);
                instancePath6.lineTo(58.0f, 6.0f);
                instancePath6.lineTo(52.0f, 6.0f);
                instancePath6.cubicTo(52.009983f, 4.0f, 52.009983f, 2.0f, 52.0f, 0.0f);
                instancePath6.lineTo(52.0f, 0.0f);
                instancePath6.close();
                WeChatSVGRenderC2Java.setFillType(instancePath6, 2);
                canvas.drawPath(instancePath6, instancePaint9);
                canvas.restore();
                canvas.save();
                Paint instancePaint10 = c.instancePaint(instancePaint3, looper);
                Path instancePath7 = c.instancePath(looper);
                instancePath7.moveTo(1.7763568E-15f, 12.0f);
                instancePath7.lineTo(6.0f, 12.0f);
                instancePath7.cubicTo(5.9900165f, 14.0f, 5.9900165f, 16.0f, 6.0f, 18.0f);
                instancePath7.lineTo(1.7763568E-15f, 18.0f);
                instancePath7.lineTo(1.7763568E-15f, 12.0f);
                instancePath7.lineTo(1.7763568E-15f, 12.0f);
                instancePath7.close();
                WeChatSVGRenderC2Java.setFillType(instancePath7, 2);
                canvas.drawPath(instancePath7, instancePaint10);
                canvas.restore();
                canvas.save();
                Paint instancePaint11 = c.instancePaint(instancePaint3, looper);
                Path instancePath8 = c.instancePath(looper);
                instancePath8.moveTo(10.0f, 12.0f);
                instancePath8.lineTo(16.0f, 12.0f);
                instancePath8.lineTo(16.0f, 18.0f);
                instancePath8.lineTo(10.0f, 18.0f);
                instancePath8.cubicTo(10.009983f, 16.0f, 10.009983f, 14.0f, 10.0f, 12.0f);
                instancePath8.lineTo(10.0f, 12.0f);
                instancePath8.close();
                WeChatSVGRenderC2Java.setFillType(instancePath8, 2);
                canvas.drawPath(instancePath8, instancePaint11);
                canvas.restore();
                canvas.save();
                Paint instancePaint12 = c.instancePaint(instancePaint3, looper);
                Path instancePath9 = c.instancePath(looper);
                instancePath9.moveTo(21.0f, 12.0f);
                instancePath9.lineTo(27.0f, 12.0f);
                instancePath9.lineTo(27.0f, 18.0f);
                instancePath9.lineTo(21.0f, 18.0f);
                instancePath9.lineTo(21.0f, 12.0f);
                instancePath9.lineTo(21.0f, 12.0f);
                instancePath9.close();
                WeChatSVGRenderC2Java.setFillType(instancePath9, 2);
                canvas.drawPath(instancePath9, instancePaint12);
                canvas.restore();
                canvas.save();
                Paint instancePaint13 = c.instancePaint(instancePaint3, looper);
                Path instancePath10 = c.instancePath(looper);
                instancePath10.moveTo(31.0f, 12.0f);
                instancePath10.lineTo(37.0f, 12.0f);
                instancePath10.lineTo(37.0f, 18.0f);
                instancePath10.lineTo(31.0f, 18.0f);
                instancePath10.lineTo(31.0f, 12.0f);
                instancePath10.lineTo(31.0f, 12.0f);
                instancePath10.close();
                WeChatSVGRenderC2Java.setFillType(instancePath10, 2);
                canvas.drawPath(instancePath10, instancePaint13);
                canvas.restore();
                canvas.save();
                Paint instancePaint14 = c.instancePaint(instancePaint3, looper);
                Path instancePath11 = c.instancePath(looper);
                instancePath11.moveTo(42.0f, 12.0f);
                instancePath11.lineTo(48.0f, 12.0f);
                instancePath11.lineTo(48.0f, 18.0f);
                instancePath11.lineTo(42.0f, 18.0f);
                instancePath11.lineTo(42.0f, 12.0f);
                instancePath11.lineTo(42.0f, 12.0f);
                instancePath11.close();
                WeChatSVGRenderC2Java.setFillType(instancePath11, 2);
                canvas.drawPath(instancePath11, instancePaint14);
                canvas.restore();
                canvas.save();
                Paint instancePaint15 = c.instancePaint(instancePaint3, looper);
                Path instancePath12 = c.instancePath(looper);
                instancePath12.moveTo(52.0f, 12.0f);
                instancePath12.lineTo(58.0f, 12.0f);
                instancePath12.lineTo(58.0f, 18.0f);
                instancePath12.lineTo(52.0f, 18.0f);
                instancePath12.cubicTo(52.009983f, 16.0f, 52.009983f, 14.0f, 52.0f, 12.0f);
                instancePath12.lineTo(52.0f, 12.0f);
                instancePath12.close();
                WeChatSVGRenderC2Java.setFillType(instancePath12, 2);
                canvas.drawPath(instancePath12, instancePaint15);
                canvas.restore();
                canvas.save();
                Paint instancePaint16 = c.instancePaint(instancePaint3, looper);
                Path instancePath13 = c.instancePath(looper);
                instancePath13.moveTo(10.0f, 24.0f);
                instancePath13.lineTo(48.0f, 24.0f);
                instancePath13.cubicTo(47.989872f, 25.99852f, 47.989872f, 27.99704f, 48.0f, 30.0f);
                instancePath13.cubicTo(35.329956f, 30.005552f, 22.670042f, 29.99556f, 10.0f, 30.0f);
                instancePath13.cubicTo(10.010128f, 27.99704f, 10.010128f, 25.99852f, 10.0f, 24.0f);
                instancePath13.lineTo(10.0f, 24.0f);
                instancePath13.close();
                WeChatSVGRenderC2Java.setFillType(instancePath13, 2);
                canvas.drawPath(instancePath13, instancePaint16);
                canvas.restore();
                canvas.restore();
                c.done(looper);
                break;
        }
        return 0;
    }
}
