package com.tencent.mm.plugin.recordvideo.plugin.parent;

import android.os.Bundle;
import com.tencent.matrix.trace.core.AppMethodBeat;
import com.tencent.mm.plugin.appbrand.jsapi.k.g;
import com.tencent.mm.plugin.appbrand.jsapi.k.r;
import com.tencent.thumbplayer.api.TPOptionalID;
import com.tencent.thumbplayer.core.common.TPCodecParamers;

public interface d {
    public static final a BUp = a.BUq;

    void a(c cVar, Bundle bundle);

    public static final class c extends Enum<c> {
        public static final c BUA;
        public static final c BUB;
        public static final c BUC;
        public static final c BUD;
        public static final c BUE;
        public static final c BUF;
        public static final c BUG;
        public static final c BUH;
        public static final c BUI;
        public static final c BUJ;
        public static final c BUK;
        public static final c BUL;
        public static final c BUM;
        public static final c BUN;
        public static final c BUO;
        public static final c BUP;
        public static final c BUQ;
        public static final c BUR;
        public static final c BUS;
        public static final c BUT;
        public static final c BUU;
        public static final c BUV;
        public static final c BUW;
        public static final c BUX;
        public static final c BUY;
        public static final c BUZ;
        public static final c BUr;
        public static final c BUs;
        public static final c BUt;
        public static final c BUu;
        public static final c BUv;
        public static final c BUw;
        public static final c BUx;
        public static final c BUy;
        public static final c BUz;
        public static final c BVA;
        public static final c BVB;
        public static final c BVC;
        public static final c BVD;
        public static final c BVE;
        public static final c BVF;
        public static final c BVG;
        public static final c BVH;
        public static final c BVI;
        public static final c BVJ;
        public static final c BVK;
        public static final c BVL;
        public static final c BVM;
        public static final c BVN;
        public static final c BVO;
        public static final c BVP;
        public static final c BVQ;
        public static final c BVR;
        public static final c BVS;
        public static final c BVT;
        public static final c BVU;
        public static final c BVV;
        public static final c BVW;
        public static final c BVX;
        public static final c BVY;
        public static final c BVZ;
        public static final c BVa;
        public static final c BVb;
        public static final c BVc;
        public static final c BVd;
        public static final c BVe;
        public static final c BVf;
        public static final c BVg;
        public static final c BVh;
        public static final c BVi;
        public static final c BVj;
        public static final c BVk;
        public static final c BVl;
        public static final c BVm;
        public static final c BVn;
        public static final c BVo;
        public static final c BVp;
        public static final c BVq;
        public static final c BVr;
        public static final c BVs;
        public static final c BVt;
        public static final c BVu;
        public static final c BVv;
        public static final c BVw;
        public static final c BVx;
        public static final c BVy;
        public static final c BVz;
        public static final c BWA;
        public static final c BWB;
        public static final c BWC;
        public static final c BWD;
        public static final c BWE;
        public static final c BWF;
        public static final c BWG;
        public static final c BWH;
        public static final c BWI;
        public static final c BWJ;
        public static final c BWK;
        public static final c BWL;
        public static final c BWM;
        public static final c BWN;
        public static final c BWO;
        public static final c BWP;
        public static final c BWQ;
        public static final c BWR;
        public static final c BWS;
        public static final c BWT;
        public static final c BWU;
        public static final c BWV;
        public static final c BWW;
        private static final /* synthetic */ c[] BWX;
        public static final c BWa;
        public static final c BWb;
        public static final c BWc;
        public static final c BWd;
        public static final c BWe;
        public static final c BWf;
        public static final c BWg;
        public static final c BWh;
        public static final c BWi;
        public static final c BWj;
        public static final c BWk;
        public static final c BWl;
        public static final c BWm;
        public static final c BWn;
        public static final c BWo;
        public static final c BWp;
        public static final c BWq;
        public static final c BWr;
        public static final c BWs;
        public static final c BWt;
        public static final c BWu;
        public static final c BWv;
        public static final c BWw;
        public static final c BWx;
        public static final c BWy;
        public static final c BWz;

        static {
            AppMethodBeat.i(75782);
            c[] cVarArr = new c[r.CTRL_INDEX];
            c cVar = new c("PREPARE_CAMERA_ZOOM", 0);
            BUr = cVar;
            cVarArr[0] = cVar;
            c cVar2 = new c("TRIGGER_CAMERA_ZOOM", 1);
            BUs = cVar2;
            cVarArr[1] = cVar2;
            c cVar3 = new c("SWITCH_CAMERA", 2);
            BUt = cVar3;
            cVarArr[2] = cVar3;
            c cVar4 = new c("FOCUS_ON_TOUCH", 3);
            BUu = cVar4;
            cVarArr[3] = cVar4;
            c cVar5 = new c("RECORD_START", 4);
            BUv = cVar5;
            cVarArr[4] = cVar5;
            c cVar6 = new c("RECORD_FINISH", 5);
            BUw = cVar6;
            cVarArr[5] = cVar6;
            c cVar7 = new c("SUB_RECORD_FINISH", 6);
            BUx = cVar7;
            cVarArr[6] = cVar7;
            c cVar8 = new c("SUB_RECORD_PREPARE_DELETE", 7);
            BUy = cVar8;
            cVarArr[7] = cVar8;
            c cVar9 = new c("SUB_RECORD_CANCEL_DELETE", 8);
            BUz = cVar9;
            cVarArr[8] = cVar9;
            c cVar10 = new c("SUB_RECORD_DELETE", 9);
            BUA = cVar10;
            cVarArr[9] = cVar10;
            c cVar11 = new c("SUB_RECORD_SELECT", 10);
            BUB = cVar11;
            cVarArr[10] = cVar11;
            c cVar12 = new c("SUB_RECORD_CAMERA", 11);
            BUC = cVar12;
            cVarArr[11] = cVar12;
            c cVar13 = new c("RECORD_PICTURE", 12);
            BUD = cVar13;
            cVarArr[12] = cVar13;
            c cVar14 = new c("RECORD_ROUTE", 13);
            BUE = cVar14;
            cVarArr[13] = cVar14;
            c cVar15 = new c("RECORD_BEAUTIFY", 14);
            BUF = cVar15;
            cVarArr[14] = cVar15;
            c cVar16 = new c("RECORD_FILTER", 15);
            BUG = cVar16;
            cVarArr[15] = cVar16;
            c cVar17 = new c("RECORD_CLICK_MUSIC", 16);
            BUH = cVar17;
            cVarArr[16] = cVar17;
            c cVar18 = new c("RECORD_UN_CLICK_MUSIC", 17);
            BUI = cVar18;
            cVarArr[17] = cVar18;
            c cVar19 = new c("RECORD_STICKER_PANEL", 18);
            BUJ = cVar19;
            cVarArr[18] = cVar19;
            c cVar20 = new c("RECORD_CHANGE_STICKER", 19);
            BUK = cVar20;
            cVarArr[19] = cVar20;
            c cVar21 = new c("TO_SET_RESULT", 20);
            BUL = cVar21;
            cVarArr[20] = cVar21;
            c cVar22 = new c("RECORD_TYPE_CHANGE", 21);
            BUM = cVar22;
            cVarArr[21] = cVar22;
            c cVar23 = new c("RECORD_START_COUNTDOWN", 22);
            BUN = cVar23;
            cVarArr[22] = cVar23;
            c cVar24 = new c("RECORD_CANCEL_COUNTDOWN", 23);
            BUO = cVar24;
            cVarArr[23] = cVar24;
            c cVar25 = new c("RECORD_FINISH_COUNTDOWN", 24);
            BUP = cVar25;
            cVarArr[24] = cVar25;
            c cVar26 = new c("BACK_RECORD", 25);
            BUQ = cVar26;
            cVarArr[25] = cVar26;
            c cVar27 = new c("START_PLAY_VIDEO", 26);
            BUR = cVar27;
            cVarArr[26] = cVar27;
            c cVar28 = new c("EDIT_VIDEO", 27);
            BUS = cVar28;
            cVarArr[27] = cVar28;
            c cVar29 = new c("EDIT_VIDEO_WITH_EMOJI", 28);
            BUT = cVar29;
            cVarArr[28] = cVar29;
            c cVar30 = new c("EDIT_VIDEO_WITH_TEXT", 29);
            BUU = cVar30;
            cVarArr[29] = cVar30;
            c cVar31 = new c("EDIT_VIDEO_WITH_TIP", 30);
            BUV = cVar31;
            cVarArr[30] = cVar31;
            c cVar32 = new c("EDIT_VIDEO_SEEK", 31);
            BUW = cVar32;
            cVarArr[31] = cVar32;
            c cVar33 = new c("EDIT_SHOW_EMOJI", 32);
            BUX = cVar33;
            cVarArr[32] = cVar33;
            c cVar34 = new c("EDIT_ADD_TEXT", 33);
            BUY = cVar34;
            cVarArr[33] = cVar34;
            c cVar35 = new c("EDIT_SHOW_TEXT", 34);
            BUZ = cVar35;
            cVarArr[34] = cVar35;
            c cVar36 = new c("EDIT_ADD_TEXT_CANCEL", 35);
            BVa = cVar36;
            cVarArr[35] = cVar36;
            c cVar37 = new c("EDIT_ADD_TIP", 36);
            BVb = cVar37;
            cVarArr[36] = cVar37;
            c cVar38 = new c("EDIT_ADD_POI", 37);
            BVc = cVar38;
            cVarArr[37] = cVar38;
            c cVar39 = new c("EDIT_CHANGE_TEXT", 38);
            BVd = cVar39;
            cVarArr[38] = cVar39;
            c cVar40 = new c("EDIT_CHANGE_TIP", 39);
            BVe = cVar40;
            cVarArr[39] = cVar40;
            c cVar41 = new c("EDIT_CHANGE_POI", 40);
            BVf = cVar41;
            cVarArr[40] = cVar41;
            c cVar42 = new c("EDIT_ADD_MUSIC", 41);
            BVg = cVar42;
            cVarArr[41] = cVar42;
            c cVar43 = new c("EDIT_ADD_MUSIC_DONE", 42);
            BVh = cVar43;
            cVarArr[42] = cVar43;
            c cVar44 = new c("EDIT_DELETE_ITEM", 43);
            BVi = cVar44;
            cVarArr[43] = cVar44;
            c cVar45 = new c("EDIT_IN_PREVIEW", 44);
            BVj = cVar45;
            cVarArr[44] = cVar45;
            c cVar46 = new c("EDIT_SET_ORIGIN_MUTE", 45);
            BVk = cVar46;
            cVarArr[45] = cVar46;
            c cVar47 = new c("EDIT_SELECT_MUSIC", 46);
            BVl = cVar47;
            cVarArr[46] = cVar47;
            c cVar48 = new c("EDIT_SELECT_LYRICS", 47);
            BVm = cVar48;
            cVarArr[47] = cVar48;
            c cVar49 = new c("EDIT_CROP_VIDEO", 48);
            BVn = cVar49;
            cVarArr[48] = cVar49;
            c cVar50 = new c("EDIT_FORCE_CROP_VIDEO", 49);
            BVo = cVar50;
            cVarArr[49] = cVar50;
            c cVar51 = new c("EDIT_CROP_VIDEO_LENGTH", 50);
            BVp = cVar51;
            cVarArr[50] = cVar51;
            c cVar52 = new c("EDIT_CROP_VIDEO_PERCENT", 51);
            BVq = cVar52;
            cVarArr[51] = cVar52;
            c cVar53 = new c("EDIT_CROP_VIDEO_PAUSE", 52);
            BVr = cVar53;
            cVarArr[52] = cVar53;
            c cVar54 = new c("EDIT_CROP_VIDEO_RESUME", 53);
            BVs = cVar54;
            cVarArr[53] = cVar54;
            c cVar55 = new c("EDIT_CROP_CANCEL", 54);
            BVt = cVar55;
            cVarArr[54] = cVar55;
            c cVar56 = new c("EDIT_CROP_FINISH", 55);
            BVu = cVar56;
            cVarArr[55] = cVar56;
            c cVar57 = new c("EDIT_FINISH", 56);
            BVv = cVar57;
            cVarArr[56] = cVar57;
            c cVar58 = new c("EDIT_START_MUX", 57);
            BVw = cVar58;
            cVarArr[57] = cVar58;
            c cVar59 = new c("EDIT_VIDEO_PREPARE", 58);
            BVx = cVar59;
            cVarArr[58] = cVar59;
            c cVar60 = new c("EDIT_DELETE_ITEM_DONE", 59);
            BVy = cVar60;
            cVarArr[59] = cVar60;
            c cVar61 = new c("EDIT_EXIT_POST_PREVIEW", 60);
            BVz = cVar61;
            cVarArr[60] = cVar61;
            c cVar62 = new c("EDIT_PREVIEW_MODE_CHANGE", 61);
            BVA = cVar62;
            cVarArr[61] = cVar62;
            c cVar63 = new c("EDIT_PHOTO_CROP", 62);
            BVB = cVar63;
            cVarArr[62] = cVar63;
            c cVar64 = new c("EDIT_PHOTO_SHOW_EMOJI_PANEL", 63);
            BVC = cVar64;
            cVarArr[63] = cVar64;
            c cVar65 = new c("EDIT_PHOTO_SHOW_TEXT_PANEL", 64);
            BVD = cVar65;
            cVarArr[64] = cVar65;
            c cVar66 = new c("EDIT_PHOTO_DOODLE", 65);
            BVE = cVar66;
            cVarArr[65] = cVar66;
            c cVar67 = new c("EDIT_PHOTO_DOODLE_CLICK", 66);
            BVF = cVar67;
            cVarArr[66] = cVar67;
            c cVar68 = new c("EDIT_PHOTO_DOODLE_MOVE_START", 67);
            BVG = cVar68;
            cVarArr[67] = cVar68;
            c cVar69 = new c("EDIT_PHOTO_DOODLE_MOVE_STOP", 68);
            BVH = cVar69;
            cVarArr[68] = cVar69;
            c cVar70 = new c("EDIT_PHOTO_DOODLE_CANCEL", 69);
            BVI = cVar70;
            cVarArr[69] = cVar70;
            c cVar71 = new c("EDIT_PHOTO_DOODLE_MSC", 70);
            BVJ = cVar71;
            cVarArr[70] = cVar71;
            c cVar72 = new c("EDIT_PHOTO_DOODLE_BRUSH", 71);
            BVK = cVar72;
            cVarArr[71] = cVar72;
            c cVar73 = new c("EDIT_PHOTO_DOODLE_PENCIL", 72);
            BVL = cVar73;
            cVarArr[72] = cVar73;
            c cVar74 = new c("EDIT_PHOTO_DOODLE_UNDO", 73);
            BVM = cVar74;
            cVarArr[73] = cVar74;
            c cVar75 = new c("EDIT_PHOTO_DOODLE_FINISH", 74);
            BVN = cVar75;
            cVarArr[74] = cVar75;
            c cVar76 = new c("EDIT_PHOTO_CROP_CANCEL", 75);
            BVO = cVar76;
            cVarArr[75] = cVar76;
            c cVar77 = new c("EDIT_PHOTO_CROP_FINISH", 76);
            BVP = cVar77;
            cVarArr[76] = cVar77;
            c cVar78 = new c("EDIT_PHOTO_CROP_ROTATE", 77);
            BVQ = cVar78;
            cVarArr[77] = cVar78;
            c cVar79 = new c("EDIT_PHOTO_CROP_UNDO", 78);
            BVR = cVar79;
            cVarArr[78] = cVar79;
            c cVar80 = new c("EDIT_PHOTO_SHOW_FUNC_LAYOUT", 79);
            BVS = cVar80;
            cVarArr[79] = cVar80;
            c cVar81 = new c("EDIT_PHOTO_FILTER_CANCEL", 80);
            BVT = cVar81;
            cVarArr[80] = cVar81;
            c cVar82 = new c("EDIT_PHOTO_FILTER_ENTER", 81);
            BVU = cVar82;
            cVarArr[81] = cVar82;
            c cVar83 = new c("EDIT_VLOG_SIZE_CHANGE", 82);
            BVV = cVar83;
            cVarArr[82] = cVar83;
            c cVar84 = new c("EDIT_VLOG_PREPARE", 83);
            BVW = cVar84;
            cVarArr[83] = cVar84;
            c cVar85 = new c("EDIT_VLOG_SEARCH_MUSIC_FINISH", 84);
            BVX = cVar85;
            cVarArr[84] = cVar85;
            c cVar86 = new c("EDIT_VLOG_SEARCH_MUSIC_SCRIPT_FINISH", 85);
            BVY = cVar86;
            cVarArr[85] = cVar86;
            c cVar87 = new c("EDIT_VLOG_SELECT_IMAGE_VLOG", 86);
            BVZ = cVar87;
            cVarArr[86] = cVar87;
            c cVar88 = new c("EDIT_VLOG_MULTI_IMAGE_SELECT", 87);
            BWa = cVar88;
            cVarArr[87] = cVar88;
            c cVar89 = new c("EDIT_VLOG_SELECT_TRACK", 88);
            BWb = cVar89;
            cVarArr[88] = cVar89;
            c cVar90 = new c("EDIT_VLOG_TRACK_CROP", 89);
            BWc = cVar90;
            cVarArr[89] = cVar90;
            c cVar91 = new c("EDIT_COMPOSITION_DURATION_CUT", 90);
            BWd = cVar91;
            cVarArr[90] = cVar91;
            c cVar92 = new c("EDIT_COMPOSITION_TAP_DOWN", 91);
            BWe = cVar92;
            cVarArr[91] = cVar92;
            c cVar93 = new c("EDIT_COMPOSITION_TAP_UP", 92);
            BWf = cVar93;
            cVarArr[92] = cVar93;
            c cVar94 = new c("EDIT_VLOG_SINGLE_TRACK_CROP", 93);
            BWg = cVar94;
            cVarArr[93] = cVar94;
            c cVar95 = new c("EDIT_VLOG_EDIT_TIME", 94);
            BWh = cVar95;
            cVarArr[94] = cVar95;
            c cVar96 = new c("EDIT_VLOG_EDIT_TIME_FINISH", 95);
            BWi = cVar96;
            cVarArr[95] = cVar96;
            c cVar97 = new c("EDIT_VLOG_EDIT_SPEED", 96);
            BWj = cVar97;
            cVarArr[96] = cVar97;
            c cVar98 = new c("EDIT_VLOG_CHANGE_PLAY_RANGE", 97);
            BWk = cVar98;
            cVarArr[97] = cVar98;
            c cVar99 = new c("EDIT_ADD_EMOJI", 98);
            BWl = cVar99;
            cVarArr[98] = cVar99;
            c cVar100 = new c("EDIT_TRACK_DURATION_SCALE", 99);
            BWm = cVar100;
            cVarArr[99] = cVar100;
            c cVar101 = new c("EDIT_TRACK_DURATION_SCALE_FINISH", 100);
            BWn = cVar101;
            cVarArr[100] = cVar101;
            c cVar102 = new c("EDIT_FILTER_SHOW", 101);
            BWo = cVar102;
            cVarArr[101] = cVar102;
            c cVar103 = new c("EDIT_ADD_CAPTION", 102);
            BWp = cVar103;
            cVarArr[102] = cVar103;
            c cVar104 = new c("EDIT_CAPTION", 103);
            BWq = cVar104;
            cVarArr[103] = cVar104;
            c cVar105 = new c("EDIT_SHOW_CAPTION", 104);
            BWr = cVar105;
            cVarArr[104] = cVar105;
            c cVar106 = new c("EDIT_UPDATE_CAPTION", 105);
            BWs = cVar106;
            cVarArr[105] = cVar106;
            c cVar107 = new c("EDIT_DELETE_CAPTION", 106);
            BWt = cVar107;
            cVarArr[106] = cVar107;
            c cVar108 = new c("EDIT_CANCEL_CAPTION", 107);
            BWu = cVar108;
            cVarArr[107] = cVar108;
            c cVar109 = new c("EDIT_CLICK_VIEW", 108);
            BWv = cVar109;
            cVarArr[108] = cVar109;
            c cVar110 = new c("EDIT_SHOW_TRANSITION_MARK", 109);
            BWw = cVar110;
            cVarArr[109] = cVar110;
            c cVar111 = new c("EDIT_HIDE_TRANSITION_MARK", 110);
            BWx = cVar111;
            cVarArr[110] = cVar111;
            c cVar112 = new c("EDIT_SELECT_TRANSITION", 111);
            BWy = cVar112;
            cVarArr[111] = cVar112;
            c cVar113 = new c("EDIT_UNSELECT_TRANSITION", 112);
            BWz = cVar113;
            cVarArr[112] = cVar113;
            c cVar114 = new c("EDIT_REFRESH_TRANSITION_MARK_STATUS", 113);
            BWA = cVar114;
            cVarArr[113] = cVar114;
            c cVar115 = new c("EDIT_SET_TRANSITION", 114);
            BWB = cVar115;
            cVarArr[114] = cVar115;
            c cVar116 = new c("EDIT_APPLY_ALL_TRANSITION", 115);
            BWC = cVar116;
            cVarArr[115] = cVar116;
            c cVar117 = new c("EDIT_ENTER_VOICE_RECORD_PANEL", 116);
            BWD = cVar117;
            cVarArr[116] = cVar117;
            c cVar118 = new c("EDIT_EXIT_VOICE_RECORD_PANEL", 117);
            BWE = cVar118;
            cVarArr[117] = cVar118;
            c cVar119 = new c("EDIT_APPLY_VOICE_RECORD", 118);
            BWF = cVar119;
            cVarArr[118] = cVar119;
            c cVar120 = new c("EDIT_ADD_PAG_STICKER", 119);
            BWG = cVar120;
            cVarArr[119] = cVar120;
            c cVar121 = new c("EDIT_CHANGE_PAG_TEXT", 120);
            BWH = cVar121;
            cVarArr[120] = cVar121;
            c cVar122 = new c("EDIT_UPDATE_PAG_TEXT", 121);
            BWI = cVar122;
            cVarArr[121] = cVar122;
            c cVar123 = new c("EDIT_FINISH_PAG_MAGIC", 122);
            BWJ = cVar123;
            cVarArr[122] = cVar123;
            c cVar124 = new c("EDIT_SHOW_TRANSITION_PANEL", 123);
            BWK = cVar124;
            cVarArr[123] = cVar124;
            c cVar125 = new c("EDIT_HIDE_OPERATION", 124);
            BWL = cVar125;
            cVarArr[124] = cVar125;
            c cVar126 = new c("EDIT_SHOW_OPERATION", 125);
            BWM = cVar126;
            cVarArr[125] = cVar126;
            c cVar127 = new c("EDIT_START_TTS", 126);
            BWN = cVar127;
            cVarArr[126] = cVar127;
            c cVar128 = new c("EDIT_END_TTS", TPOptionalID.OPTION_ID_BEFORE_BOOL_ENABLE_AUDIO_PASSTHROUGH);
            BWO = cVar128;
            cVarArr[127] = cVar128;
            c cVar129 = new c("EDIT_CANCEL_TTS", 128);
            BWP = cVar129;
            cVarArr[128] = cVar129;
            c cVar130 = new c("EDIT_REMOVE_TTS", 129);
            BWQ = cVar130;
            cVarArr[129] = cVar130;
            c cVar131 = new c("EDIT_SELECT_TEMPLATE_MODE", 130);
            BWR = cVar131;
            cVarArr[130] = cVar131;
            c cVar132 = new c("EDIT_SELECT_NORMAL_MODE", TPCodecParamers.TP_PROFILE_MPEG2_AAC_HE);
            BWS = cVar132;
            cVarArr[131] = cVar132;
            c cVar133 = new c("EDIT_CHOOSE_TEMPLATE", 132);
            BWT = cVar133;
            cVarArr[132] = cVar133;
            c cVar134 = new c("EDIT_VIDEO_ENHANCEMENT", 133);
            BWU = cVar134;
            cVarArr[133] = cVar134;
            c cVar135 = new c("EDIT_SHOW_ADD_MUSIC", g.CTRL_INDEX);
            BWV = cVar135;
            cVarArr[134] = cVar135;
            c cVar136 = new c("UI_FINISH", com.tencent.mm.plugin.appbrand.jsapi.k.c.CTRL_INDEX);
            BWW = cVar136;
            cVarArr[135] = cVar136;
            BWX = cVarArr;
            AppMethodBeat.o(75782);
        }

        public static c valueOf(String str) {
            AppMethodBeat.i(75784);
            c cVar = (c) Enum.valueOf(c.class, str);
            AppMethodBeat.o(75784);
            return cVar;
        }

        public static c[] values() {
            AppMethodBeat.i(75783);
            c[] cVarArr = (c[]) BWX.clone();
            AppMethodBeat.o(75783);
            return cVarArr;
        }

        private c(String str, int i2) {
            super(str, i2);
        }
    }

    public static final class a {
        static final /* synthetic */ a BUq = new a();

        static {
            AppMethodBeat.i(75780);
            AppMethodBeat.o(75780);
        }

        private a() {
        }
    }

    public static final class b {
        public static /* synthetic */ void a(d dVar, c cVar) {
            AppMethodBeat.i(75781);
            dVar.a(cVar, null);
            AppMethodBeat.o(75781);
        }
    }
}
