name: MM
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install json dependencies
        run: |
          - apt-get update -y
          - apt-get install jq -y
      - name: Get the latest jadx
        run: |
          bash ./get_jadx.sh
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Grant execute permission for get_latest_mm.py
        run: |
          - chmod +x ./get_latest_mm.py
      - name: Run get_latest_mm.py
        run: |
          - python ./get_latest_mm.py

      - name: Check File
        run: |
          -  if ls *.apk >/dev/null 2>&1;then echo "Find File OK"; else exit; fi
      - name: Grant execute permission for jadx
        run: |
          - chmod +x ./jadx/bin/jadx
      - name: Run jadx
        run: |
          ./jadx/bin/jadx -e ./mm.apk
      - name: Commit
          version = $(jq .version mm.version)
          git checkout -b ${version}
          git rm -r --cached .
          git add ./mm
          git config --global user.name "JiZhi"
          git config --global user.email "2590970043@qq.com"
          git commit -m
          git push -u origin master




